"""add payroll finance compliance schema

Revision ID: 4a0b2d8c3f21
Revises: 3f9a1c7b2e10
Created: 2026-09-02 08:21:58.473100
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "4a0b2d8c3f21"
down_revision: str | Sequence[str] | None = "3f9a1c7b2e10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compliance_overrides",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column("override_type", sa.Text(), nullable=False),
        sa.Column("employee_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by_app_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "override_type IN ('payroll_sif', 'roster_publish')",
            name=op.f("ck_compliance_overrides_override_type"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_compliance_overrides_branch_id_branches"),
            ondelete="SET NULL (branch_id)",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_compliance_overrides_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_compliance_overrides_created_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compliance_overrides")),
    )
    op.create_index(
        "ix_compliance_overrides_company_id_branch_id",
        "compliance_overrides",
        ["company_id", "branch_id"],
        unique=False,
    )
    op.create_table(
        "nafis_reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Text(), nullable=False),
        sa.Column("total_headcount", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("emirati_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "ratio_percent",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "required_percent",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("compliant", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ratio_percent BETWEEN 0 AND 100 AND required_percent BETWEEN 0 AND 100",
            name=op.f("ck_nafis_reports_percentages"),
        ),
        sa.CheckConstraint(
            "total_headcount >= 0 AND emirati_count >= 0 AND emirati_count <= total_headcount",
            name=op.f("ck_nafis_reports_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_nafis_reports_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_nafis_reports_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nafis_reports")),
        sa.UniqueConstraint("branch_id", "period", name="uq_nafis_reports_branch_id_period"),
    )
    op.create_index(
        "ix_nafis_reports_branch_id_period",
        "nafis_reports",
        ["branch_id", sa.literal_column("period DESC")],
        unique=False,
    )
    op.create_table(
        "payroll_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Text(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("sequence_no", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("scr_bank_routing_code", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("run_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "total_disbursed",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("employee_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("wps_status", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("wps_submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("wps_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("wps_reference_no", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("approval_status", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("submitted_for_approval_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(rejected_at IS NULL AND rejected_by_app_user_id IS NULL AND rejection_reason = '') "
            "OR (rejected_at IS NOT NULL AND rejected_by_app_user_id IS NOT NULL "
            "AND btrim(rejection_reason) <> '')",
            name=op.f("ck_payroll_runs_rejection_fields"),
        ),
        sa.CheckConstraint(
            "approval_status <> 'approved' OR (approved_by_app_user_id IS NOT NULL "
            "AND approved_at IS NOT NULL)",
            name=op.f("ck_payroll_runs_approval_fields"),
        ),
        sa.CheckConstraint(
            "approval_status <> 'pending_approval' OR (submitted_by_app_user_id IS NOT NULL "
            "AND submitted_for_approval_at IS NOT NULL)",
            name=op.f("ck_payroll_runs_submission_fields"),
        ),
        sa.CheckConstraint(
            "approval_status IN ('draft', 'pending_approval', 'approved')",
            name=op.f("ck_payroll_runs_approval_status"),
        ),
        sa.CheckConstraint(
            "status <> 'generated' OR (approval_status = 'approved' "
            "AND approved_by_app_user_id IS NOT NULL AND approved_at IS NOT NULL)",
            name=op.f("ck_payroll_runs_generated_fields"),
        ),
        sa.CheckConstraint("status IN ('draft', 'generated')", name=op.f("ck_payroll_runs_status")),
        sa.CheckConstraint(
            "wps_status IN ('draft', 'sif_generated', 'submitted', 'confirmed', "
            "'partial_rejection', 'failed')",
            name=op.f("ck_payroll_runs_wps_status"),
        ),
        sa.CheckConstraint(
            "wps_status NOT IN ('confirmed', 'partial_rejection') OR wps_confirmed_at IS NOT NULL",
            name=op.f("ck_payroll_runs_wps_confirmed_at"),
        ),
        sa.CheckConstraint(
            "wps_status NOT IN ('submitted', 'confirmed', 'partial_rejection') "
            "OR wps_submitted_at IS NOT NULL",
            name=op.f("ck_payroll_runs_wps_submitted_at"),
        ),
        sa.CheckConstraint("employee_count >= 0", name=op.f("ck_payroll_runs_employee_count")),
        sa.CheckConstraint("total_disbursed >= 0", name=op.f("ck_payroll_runs_total_disbursed")),
        sa.ForeignKeyConstraint(
            ["approved_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_payroll_runs_approved_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_payroll_runs_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payroll_runs_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rejected_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_payroll_runs_rejected_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_payroll_runs_run_by_app_user_id_app_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_payroll_runs_submitted_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_runs")),
        sa.UniqueConstraint("branch_id", "period", name="uq_payroll_runs_branch_id_period"),
        sa.UniqueConstraint(
            "id", "company_id", "branch_id", name="uq_payroll_runs_id_company_id_branch_id"
        ),
    )
    op.create_index("ix_payroll_runs_branch_id", "payroll_runs", ["branch_id"], unique=False)
    op.create_index("ix_payroll_runs_company_id", "payroll_runs", ["company_id"], unique=False)
    op.create_index("ix_payroll_runs_status", "payroll_runs", ["status"], unique=False)
    op.create_table(
        "expense_claims",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.Text(), server_default=sa.text("'other'"), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("receipt_url", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("rejection_reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("payroll_run_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manager_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manager_approved_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "manager_rejection_reason", sa.Text(), server_default=sa.text("''"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'manager_approved' OR (manager_approved_by_app_user_id IS NOT NULL "
            "AND manager_approved_at IS NOT NULL)",
            name=op.f("ck_expense_claims_manager_approved_fields"),
        ),
        sa.CheckConstraint(
            "status <> 'manager_rejected' OR (manager_approved_by_app_user_id IS NOT NULL "
            "AND manager_approved_at IS NOT NULL AND btrim(manager_rejection_reason) <> '')",
            name=op.f("ck_expense_claims_manager_rejected_fields"),
        ),
        sa.CheckConstraint(
            "status <> 'rejected' OR btrim(rejection_reason) <> ''",
            name=op.f("ck_expense_claims_rejection_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'manager_approved', 'manager_rejected', 'approved', "
            "'paid', 'rejected')",
            name=op.f("ck_expense_claims_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('approved', 'paid', 'rejected') OR (approved_by_app_user_id IS NOT "
            "NULL AND approved_at IS NOT NULL)",
            name=op.f("ck_expense_claims_hr_decision_fields"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_expense_claims_amount")),
        sa.ForeignKeyConstraint(
            ["approved_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_expense_claims_approved_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_expense_claims_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_expense_claims_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_expense_claims_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["manager_approved_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_expense_claims_manager_approved_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payroll_run_id", "company_id", "branch_id"],
            ["payroll_runs.id", "payroll_runs.company_id", "payroll_runs.branch_id"],
            name=op.f("fk_expense_claims_payroll_run_id_payroll_runs"),
            ondelete="SET NULL (payroll_run_id)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_claims")),
    )
    op.create_index("ix_expense_claims_branch_id", "expense_claims", ["branch_id"], unique=False)
    op.create_index(
        "ix_expense_claims_employee_id", "expense_claims", ["employee_id"], unique=False
    )
    op.create_index("ix_expense_claims_status", "expense_claims", ["status"], unique=False)
    op.create_table(
        "payroll_approval_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("payroll_run_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("performed_by_app_user_id", sa.UUID(), nullable=False),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('submitted', 'approved', 'rejected', 'recalled')",
            name=op.f("ck_payroll_approval_log_action"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_payroll_approval_log_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payroll_approval_log_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payroll_run_id", "company_id", "branch_id"],
            ["payroll_runs.id", "payroll_runs.company_id", "payroll_runs.branch_id"],
            name=op.f("fk_payroll_approval_log_payroll_run_id_payroll_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_payroll_approval_log_performed_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_approval_log")),
    )
    op.create_index(
        "ix_payroll_approval_log_payroll_run_id_created_at",
        "payroll_approval_log",
        ["payroll_run_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "payroll_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("payroll_run_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column(
            "basic_salary",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "housing_allowance",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "transport_allowance",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "allowance",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "increment",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "bonus", sa.Numeric(precision=12, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "other_pay",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "leave_deduction",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "variable_allowance",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "additional_allowances",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "deductions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("excluded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "wps_payment_status", sa.Text(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("wps_rejection_reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "wps_payment_status <> 'rejected' OR btrim(wps_rejection_reason) <> ''",
            name=op.f("ck_payroll_entries_wps_rejection_reason"),
        ),
        sa.CheckConstraint(
            "wps_payment_status IN ('pending', 'paid', 'rejected')",
            name=op.f("ck_payroll_entries_wps_payment_status"),
        ),
        sa.CheckConstraint("allowance >= 0", name=op.f("ck_payroll_entries_allowance")),
        sa.CheckConstraint("basic_salary >= 0", name=op.f("ck_payroll_entries_basic_salary")),
        sa.CheckConstraint("bonus >= 0", name=op.f("ck_payroll_entries_bonus")),
        sa.CheckConstraint(
            "housing_allowance >= 0", name=op.f("ck_payroll_entries_housing_allowance")
        ),
        sa.CheckConstraint("increment >= 0", name=op.f("ck_payroll_entries_increment")),
        sa.CheckConstraint("leave_deduction >= 0", name=op.f("ck_payroll_entries_leave_deduction")),
        sa.CheckConstraint("other_pay >= 0", name=op.f("ck_payroll_entries_other_pay")),
        sa.CheckConstraint(
            "transport_allowance >= 0", name=op.f("ck_payroll_entries_transport_allowance")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_payroll_entries_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payroll_entries_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_payroll_entries_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payroll_run_id", "company_id", "branch_id"],
            ["payroll_runs.id", "payroll_runs.company_id", "payroll_runs.branch_id"],
            name=op.f("fk_payroll_entries_payroll_run_id_payroll_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_entries")),
        sa.UniqueConstraint(
            "payroll_run_id", "employee_id", name="uq_payroll_entries_payroll_run_id_employee_id"
        ),
    )
    op.create_index(
        "ix_payroll_entries_employee_id", "payroll_entries", ["employee_id"], unique=False
    )
    op.create_index(
        "ix_payroll_entries_payroll_run_id", "payroll_entries", ["payroll_run_id"], unique=False
    )
    op.create_table(
        "payslips",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("payroll_run_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Text(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column(
            "gross_pay",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "net_pay",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "data_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("gross_pay >= 0", name=op.f("ck_payslips_gross_pay")),
        sa.CheckConstraint("net_pay >= 0", name=op.f("ck_payslips_net_pay")),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_payslips_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payslips_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_payslips_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payroll_run_id", "company_id", "branch_id"],
            ["payroll_runs.id", "payroll_runs.company_id", "payroll_runs.branch_id"],
            name=op.f("fk_payslips_payroll_run_id_payroll_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payslips")),
        sa.UniqueConstraint(
            "payroll_run_id", "employee_id", name="uq_payslips_payroll_run_id_employee_id"
        ),
    )
    op.create_index(
        "ix_payslips_employee_id_period",
        "payslips",
        ["employee_id", sa.literal_column("period DESC")],
        unique=False,
    )
    op.create_table(
        "salary_advances",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("disbursed_date", sa.Date(), nullable=True),
        sa.Column(
            "repayment_start_month",
            sa.Date(),
            server_default=sa.text("date_trunc('month', CURRENT_DATE)::date"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("repayment_months", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "monthly_deduction",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "outstanding_balance",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "repayment_start_month = date_trunc('month', repayment_start_month)::date",
            name=op.f("ck_salary_advances_repayment_start_month"),
        ),
        sa.CheckConstraint(
            "status <> 'cancelled' OR coalesce(btrim(rejection_reason), '') <> ''",
            name=op.f("ck_salary_advances_cancelled_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'settled', 'cancelled')",
            name=op.f("ck_salary_advances_status"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_salary_advances_amount")),
        sa.CheckConstraint(
            "monthly_deduction >= 0", name=op.f("ck_salary_advances_monthly_deduction")
        ),
        sa.CheckConstraint(
            "outstanding_balance >= 0", name=op.f("ck_salary_advances_outstanding_balance")
        ),
        sa.CheckConstraint(
            "repayment_months > 0", name=op.f("ck_salary_advances_repayment_months")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_salary_advances_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_salary_advances_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_salary_advances_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_salary_advances")),
        sa.UniqueConstraint(
            "id", "company_id", "branch_id", name="uq_salary_advances_id_company_id_branch_id"
        ),
    )
    op.create_index("ix_salary_advances_branch_id", "salary_advances", ["branch_id"], unique=False)
    op.create_index(
        "ix_salary_advances_employee_id", "salary_advances", ["employee_id"], unique=False
    )
    op.create_index("ix_salary_advances_status", "salary_advances", ["status"], unique=False)
    op.create_table(
        "advance_repayments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("advance_id", sa.UUID(), nullable=False),
        sa.Column("payroll_run_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_advance_repayments_amount")),
        sa.ForeignKeyConstraint(
            ["advance_id", "company_id", "branch_id"],
            ["salary_advances.id", "salary_advances.company_id", "salary_advances.branch_id"],
            name=op.f("fk_advance_repayments_advance_id_salary_advances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_advance_repayments_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_advance_repayments_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payroll_run_id", "company_id", "branch_id"],
            ["payroll_runs.id", "payroll_runs.company_id", "payroll_runs.branch_id"],
            name=op.f("fk_advance_repayments_payroll_run_id_payroll_runs"),
            ondelete="SET NULL (payroll_run_id)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advance_repayments")),
        sa.UniqueConstraint(
            "advance_id", "idempotency_key", name="uq_advance_repayments_advance_id_idempotency_key"
        ),
    )
    op.create_index(
        "ix_advance_repayments_advance_id", "advance_repayments", ["advance_id"], unique=False
    )
    op.create_index(
        "ix_advance_repayments_company_id_branch_id",
        "advance_repayments",
        ["company_id", "branch_id"],
        unique=False,
    )
    op.create_index(
        "ix_advance_repayments_payroll_run_id",
        "advance_repayments",
        ["payroll_run_id"],
        unique=False,
    )
    op.create_index(
        "uq_advance_repayment_payroll",
        "advance_repayments",
        ["advance_id", "payroll_run_id"],
        unique=True,
        postgresql_where=sa.text("payroll_run_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_advance_repayment_payroll",
        table_name="advance_repayments",
        postgresql_where=sa.text("payroll_run_id IS NOT NULL"),
    )
    op.drop_index("ix_advance_repayments_payroll_run_id", table_name="advance_repayments")
    op.drop_index("ix_advance_repayments_company_id_branch_id", table_name="advance_repayments")
    op.drop_index("ix_advance_repayments_advance_id", table_name="advance_repayments")
    op.drop_table("advance_repayments")
    op.drop_index("ix_salary_advances_status", table_name="salary_advances")
    op.drop_index("ix_salary_advances_employee_id", table_name="salary_advances")
    op.drop_index("ix_salary_advances_branch_id", table_name="salary_advances")
    op.drop_table("salary_advances")
    op.drop_index("ix_payslips_employee_id_period", table_name="payslips")
    op.drop_table("payslips")
    op.drop_index("ix_payroll_entries_payroll_run_id", table_name="payroll_entries")
    op.drop_index("ix_payroll_entries_employee_id", table_name="payroll_entries")
    op.drop_table("payroll_entries")
    op.drop_index(
        "ix_payroll_approval_log_payroll_run_id_created_at", table_name="payroll_approval_log"
    )
    op.drop_table("payroll_approval_log")
    op.drop_index("ix_expense_claims_status", table_name="expense_claims")
    op.drop_index("ix_expense_claims_employee_id", table_name="expense_claims")
    op.drop_index("ix_expense_claims_branch_id", table_name="expense_claims")
    op.drop_table("expense_claims")
    op.drop_index("ix_payroll_runs_status", table_name="payroll_runs")
    op.drop_index("ix_payroll_runs_company_id", table_name="payroll_runs")
    op.drop_index("ix_payroll_runs_branch_id", table_name="payroll_runs")
    op.drop_table("payroll_runs")
    op.drop_index("ix_nafis_reports_branch_id_period", table_name="nafis_reports")
    op.drop_table("nafis_reports")
    op.drop_index("ix_compliance_overrides_company_id_branch_id", table_name="compliance_overrides")
    op.drop_table("compliance_overrides")
    # ### end Alembic commands ###
