"""add leave schema

Revision ID: 5b1c3e9d4a32
Revises: 4a0b2d8c3f21
Created: 2026-09-02 08:28:51.177152
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5b1c3e9d4a32"
down_revision: str | Sequence[str] | None = "4a0b2d8c3f21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leave_settings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column(
            "leave_year_type", sa.Text(), server_default=sa.text("'calendar'"), nullable=False
        ),
        sa.Column(
            "weekend_definition", sa.Text(), server_default=sa.text("'fri-sat'"), nullable=False
        ),
        sa.Column(
            "carry_forward_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "carry_forward_max_days", sa.Integer(), server_default=sa.text("15"), nullable=False
        ),
        sa.Column("approval_chain", sa.Text(), server_default=sa.text("'1-level'"), nullable=False),
        sa.Column("ramadan_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ramadan_start", sa.Date(), nullable=True),
        sa.Column("ramadan_end", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "approval_chain IN ('1-level', '2-level')",
            name=op.f("ck_leave_settings_approval_chain"),
        ),
        sa.CheckConstraint(
            "weekend_definition IN ('fri-sat', 'sat-sun')",
            name=op.f("ck_leave_settings_weekend_definition"),
        ),
        sa.CheckConstraint(
            "ramadan_end IS NULL OR ramadan_start IS NULL OR ramadan_end >= ramadan_start",
            name=op.f("ck_leave_settings_ramadan_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_leave_settings_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_leave_settings_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_settings")),
        sa.UniqueConstraint("branch_id", name="uq_leave_settings_branch_id"),
    )
    op.create_index(
        "ix_leave_settings_company_id_branch_id",
        "leave_settings",
        ["company_id", "branch_id"],
        unique=False,
    )
    op.create_table(
        "leave_types",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), server_default=sa.text("'#6b7280'"), nullable=False),
        sa.Column("is_paid", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_unlimited", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "requires_approval", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "requires_attachment", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("requires_reason", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("min_notice_days", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "annual_entitlement_days",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("accrual_type", sa.Text(), server_default=sa.text("'fixed'"), nullable=False),
        sa.Column(
            "day_count_type", sa.Text(), server_default=sa.text("'calendar'"), nullable=False
        ),
        sa.Column("auto_approve", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "carry_forward_allowed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "carry_forward_max_days", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("gender_restriction", sa.Text(), nullable=True),
        sa.Column("min_service_months", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("once_per_career", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "not_deducted_from_annual",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("affects_payroll", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("law_reference", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "probation_eligible", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "min_notice_days >= 0 AND annual_entitlement_days >= 0 "
            "AND carry_forward_max_days >= 0 AND min_service_months >= 0",
            name=op.f("ck_leave_types_nonnegative_rules"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_leave_types_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_leave_types_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_types")),
        sa.UniqueConstraint("branch_id", "code", name="uq_leave_types_branch_id_code"),
        sa.UniqueConstraint(
            "id", "company_id", "branch_id", name="uq_leave_types_id_company_id_branch_id"
        ),
    )
    op.create_index(
        "ix_leave_types_branch_id_active_sort",
        "leave_types",
        ["branch_id", "is_active", "sort_order"],
        unique=False,
    )
    op.create_table(
        "public_holidays",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), server_default=sa.text("'federal'"), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "year = extract(year FROM date)::integer", name=op.f("ck_public_holidays_year")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_public_holidays_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_public_holidays_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_public_holidays")),
        sa.UniqueConstraint("branch_id", "date", name="uq_public_holidays_branch_id_date"),
    )
    op.create_index(
        "ix_public_holidays_branch_id_date", "public_holidays", ["branch_id", "date"], unique=False
    )
    op.create_table(
        "leave_approval_delegates",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("approver_employee_id", sa.UUID(), nullable=False),
        sa.Column("delegate_employee_id", sa.UUID(), nullable=False),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "approver_employee_id <> delegate_employee_id",
            name=op.f("ck_leave_approval_delegates_distinct"),
        ),
        sa.CheckConstraint("to_date >= from_date", name=op.f("ck_leave_approval_delegates_dates")),
        sa.ForeignKeyConstraint(
            ["approver_employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name="fk_leave_approval_delegates_approver_employee_id_employees",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_leave_approval_delegates_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_leave_approval_delegates_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["delegate_employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name="fk_leave_approval_delegates_delegate_employee_id_employees",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_approval_delegates")),
    )
    op.create_index(
        "ix_leave_approval_delegates_approver_dates",
        "leave_approval_delegates",
        ["approver_employee_id", "from_date", "to_date"],
        unique=False,
    )
    op.create_index(
        "ix_leave_approval_delegates_delegate_dates",
        "leave_approval_delegates",
        ["delegate_employee_id", "from_date", "to_date"],
        unique=False,
    )
    op.create_table(
        "leave_balances",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_id", sa.UUID(), nullable=False),
        sa.Column("leave_year", sa.Integer(), nullable=False),
        sa.Column(
            "entitled_days",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "accrued_days",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "used_days",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "pending_days",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "carried_forward",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "remaining_days",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "sick_full_pay_used",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "sick_half_pay_used",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "sick_unpaid_used",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("hajj_taken", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entitled_days >= 0 AND accrued_days >= 0 AND used_days >= 0 AND pending_days >= 0 "
            "AND carried_forward >= 0 AND remaining_days >= 0 AND sick_full_pay_used >= 0 "
            "AND sick_half_pay_used >= 0 AND sick_unpaid_used >= 0",
            name=op.f("ck_leave_balances_nonnegative_days"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_leave_balances_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_leave_balances_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_leave_balances_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["leave_type_id", "company_id", "branch_id"],
            ["leave_types.id", "leave_types.company_id", "leave_types.branch_id"],
            name=op.f("fk_leave_balances_leave_type_id_leave_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_balances")),
        sa.UniqueConstraint(
            "employee_id",
            "leave_type_id",
            "leave_year",
            name="uq_leave_balances_employee_id_leave_type_id_leave_year",
        ),
    )
    op.create_index(
        "ix_leave_balances_branch_id_year",
        "leave_balances",
        ["branch_id", "leave_year"],
        unique=False,
    )
    op.create_index(
        "ix_leave_balances_employee_id", "leave_balances", ["employee_id"], unique=False
    )
    op.create_table(
        "leave_requests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("is_half_day", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("half_day_period", sa.Text(), nullable=True),
        sa.Column(
            "days_requested",
            sa.Numeric(precision=6, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'Pending'"), nullable=False),
        sa.Column("reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("attachment_url", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("rejection_reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("approved_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("relationship", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("deceased_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("date_of_death", sa.Date(), nullable=True),
        sa.Column("child_birth_date", sa.Date(), nullable=True),
        sa.Column("child_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("expected_due_date", sa.Date(), nullable=True),
        sa.Column("institution_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("exam_dates", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("manager_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manager_approved_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "manager_rejection_reason", sa.Text(), server_default=sa.text("''"), nullable=False
        ),
        sa.Column("substitute_employee_id", sa.UUID(), nullable=True),
        sa.Column(
            "approval_level_required", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("approval_comment", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(NOT is_half_day AND half_day_period IS NULL) "
            "OR (is_half_day AND half_day_period IN ('AM', 'PM'))",
            name=op.f("ck_leave_requests_half_day"),
        ),
        sa.CheckConstraint(
            "status <> 'Approved' OR (approved_by_app_user_id IS NOT NULL "
            "AND approved_at IS NOT NULL)",
            name=op.f("ck_leave_requests_approved_fields"),
        ),
        sa.CheckConstraint(
            "status <> 'ManagerApproved' OR (manager_approved_by_app_user_id IS NOT NULL "
            "AND manager_approved_at IS NOT NULL)",
            name=op.f("ck_leave_requests_manager_approved_fields"),
        ),
        sa.CheckConstraint(
            "status <> 'ManagerRejected' OR (manager_approved_by_app_user_id IS NOT NULL "
            "AND manager_approved_at IS NOT NULL AND btrim(manager_rejection_reason) <> '')",
            name=op.f("ck_leave_requests_manager_rejected_fields"),
        ),
        sa.CheckConstraint(
            "status <> 'Rejected' OR (approved_by_app_user_id IS NOT NULL "
            "AND approved_at IS NOT NULL AND btrim(rejection_reason) <> '')",
            name=op.f("ck_leave_requests_rejected_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('Pending', 'ManagerApproved', 'ManagerRejected', 'Approved', "
            "'Rejected', 'Cancelled')",
            name=op.f("ck_leave_requests_status"),
        ),
        sa.CheckConstraint(
            "approval_level_required >= 1", name=op.f("ck_leave_requests_approval_level")
        ),
        sa.CheckConstraint("days_requested > 0", name=op.f("ck_leave_requests_days_requested")),
        sa.CheckConstraint("end_date >= start_date", name=op.f("ck_leave_requests_dates")),
        sa.ForeignKeyConstraint(
            ["approved_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_leave_requests_approved_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_leave_requests_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_leave_requests_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_leave_requests_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["leave_type_id", "company_id", "branch_id"],
            ["leave_types.id", "leave_types.company_id", "leave_types.branch_id"],
            name=op.f("fk_leave_requests_leave_type_id_leave_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["manager_approved_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_leave_requests_manager_approved_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["substitute_employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name="fk_leave_requests_substitute_employee_id_employees",
            ondelete="SET NULL (substitute_employee_id)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_requests")),
        sa.UniqueConstraint(
            "id", "company_id", "branch_id", name="uq_leave_requests_id_company_id_branch_id"
        ),
    )
    op.create_index(
        "ix_leave_requests_branch_id_start_date",
        "leave_requests",
        ["branch_id", "start_date"],
        unique=False,
    )
    op.create_index(
        "ix_leave_requests_employee_id", "leave_requests", ["employee_id"], unique=False
    )
    op.create_index("ix_leave_requests_status", "leave_requests", ["status"], unique=False)
    op.create_table(
        "leave_audit_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("leave_request_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("actor_app_user_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("old_status", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("new_status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_leave_audit_log_actor_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_leave_audit_log_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_leave_audit_log_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["leave_request_id", "company_id", "branch_id"],
            ["leave_requests.id", "leave_requests.company_id", "leave_requests.branch_id"],
            name=op.f("fk_leave_audit_log_leave_request_id_leave_requests"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_audit_log")),
    )
    op.create_index(
        "ix_leave_audit_log_request_id_created_at",
        "leave_audit_log",
        ["leave_request_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_leave_audit_log_request_id_created_at", table_name="leave_audit_log")
    op.drop_table("leave_audit_log")
    op.drop_index("ix_leave_requests_status", table_name="leave_requests")
    op.drop_index("ix_leave_requests_employee_id", table_name="leave_requests")
    op.drop_index("ix_leave_requests_branch_id_start_date", table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_index("ix_leave_balances_employee_id", table_name="leave_balances")
    op.drop_index("ix_leave_balances_branch_id_year", table_name="leave_balances")
    op.drop_table("leave_balances")
    op.drop_index(
        "ix_leave_approval_delegates_delegate_dates", table_name="leave_approval_delegates"
    )
    op.drop_index(
        "ix_leave_approval_delegates_approver_dates", table_name="leave_approval_delegates"
    )
    op.drop_table("leave_approval_delegates")
    op.drop_index("ix_public_holidays_branch_id_date", table_name="public_holidays")
    op.drop_table("public_holidays")
    op.drop_index("ix_leave_types_branch_id_active_sort", table_name="leave_types")
    op.drop_table("leave_types")
    op.drop_index("ix_leave_settings_company_id_branch_id", table_name="leave_settings")
    op.drop_table("leave_settings")
    # ### end Alembic commands ###
