"""add attendance roster schema

Revision ID: 6c2d4f0e5b43
Revises: 5b1c3e9d4a32
Created: 2026-09-02 08:34:38.590392
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6c2d4f0e5b43"
down_revision: str | Sequence[str] | None = "5b1c3e9d4a32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance_periods",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("payroll_ready", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("open_items", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'closed' OR (closed_by_app_user_id IS NOT NULL AND closed_at IS NOT NULL)",
            name=op.f("ck_attendance_periods_closed_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'closed')", name=op.f("ck_attendance_periods_status")
        ),
        sa.CheckConstraint("open_items >= 0", name=op.f("ck_attendance_periods_open_items")),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_attendance_periods_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_attendance_periods_closed_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_attendance_periods_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_periods")),
        sa.UniqueConstraint("branch_id", "period", name="uq_attendance_periods_branch_id_period"),
    )
    op.create_index(
        "ix_attendance_periods_branch_id_period",
        "attendance_periods",
        ["branch_id", "period"],
        unique=False,
    )
    op.create_table(
        "attendance_settings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column(
            "working_days",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("ARRAY['Mon', 'Tue', 'Wed', 'Thu']"),
            nullable=False,
        ),
        sa.Column(
            "weekend_days",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("ARRAY['Fri', 'Sat']"),
            nullable=False,
        ),
        sa.Column(
            "default_hours_per_day",
            sa.Numeric(precision=4, scale=2),
            server_default=sa.text("8"),
            nullable=False,
        ),
        sa.Column("late_grace_minutes", sa.Integer(), server_default=sa.text("10"), nullable=False),
        sa.Column(
            "early_departure_grace_minutes",
            sa.Integer(),
            server_default=sa.text("10"),
            nullable=False,
        ),
        sa.Column(
            "overtime_requires_approval",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "max_daily_overtime_hours",
            sa.Numeric(precision=4, scale=2),
            server_default=sa.text("2"),
            nullable=False,
        ),
        sa.Column(
            "late_deduction_policy", sa.Text(), server_default=sa.text("'none'"), nullable=False
        ),
        sa.Column(
            "late_deduction_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("wfh_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "regularisation_max_days_per_month",
            sa.Integer(),
            server_default=sa.text("2"),
            nullable=False,
        ),
        sa.Column(
            "regularisation_window_days", sa.Integer(), server_default=sa.text("7"), nullable=False
        ),
        sa.Column(
            "biometric_api_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("biometric_api_key", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "late_deduction_policy IN ('none', 'per_minute', 'per_occurrence')",
            name=op.f("ck_attendance_settings_late_deduction_policy"),
        ),
        sa.CheckConstraint(
            "default_hours_per_day >= 0 AND late_grace_minutes >= 0 "
            "AND early_departure_grace_minutes >= 0 AND max_daily_overtime_hours >= 0 "
            "AND regularisation_max_days_per_month >= 0 AND regularisation_window_days >= 0",
            name=op.f("ck_attendance_settings_nonnegative"),
        ),
        sa.CheckConstraint(
            "late_deduction_amount >= 0", name=op.f("ck_attendance_settings_late_deduction_amount")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_attendance_settings_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_attendance_settings_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_settings")),
        sa.UniqueConstraint("branch_id", name="uq_attendance_settings_branch_id"),
    )
    op.create_index(
        "ix_attendance_settings_company_id_branch_id",
        "attendance_settings",
        ["company_id", "branch_id"],
        unique=False,
    )
    op.create_table(
        "shifts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("shift_type", sa.Text(), server_default=sa.text("'fixed'"), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("break_minutes", sa.Integer(), server_default=sa.text("60"), nullable=False),
        sa.Column(
            "expected_hours",
            sa.Numeric(precision=4, scale=2),
            server_default=sa.text("8"),
            nullable=False,
        ),
        sa.Column("late_grace_minutes", sa.Integer(), server_default=sa.text("10"), nullable=False),
        sa.Column(
            "early_departure_grace_minutes",
            sa.Integer(),
            server_default=sa.text("10"),
            nullable=False,
        ),
        sa.Column("split_start_time", sa.Time(), nullable=True),
        sa.Column("split_end_time", sa.Time(), nullable=True),
        sa.Column("is_overnight", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("min_hours_flexible", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("color", sa.Text(), server_default=sa.text("'#6366f1'"), nullable=False),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("shift_category", sa.Text(), server_default=sa.text("'morning'"), nullable=False),
        sa.Column("min_staff", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "shift_category IN ('morning', 'afternoon', 'night', 'flexible', 'split')",
            name=op.f("ck_shifts_shift_category"),
        ),
        sa.CheckConstraint(
            "shift_type IN ('fixed', 'flexible', 'split', 'overnight')",
            name=op.f("ck_shifts_shift_type"),
        ),
        sa.CheckConstraint(
            "break_minutes >= 0 AND expected_hours >= 0 AND late_grace_minutes >= 0 "
            "AND early_departure_grace_minutes >= 0 "
            "AND (min_hours_flexible IS NULL OR min_hours_flexible >= 0) AND min_staff >= 0",
            name=op.f("ck_shifts_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_shifts_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_shifts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shifts")),
        sa.UniqueConstraint("branch_id", "name", name="uq_shifts_branch_id_name"),
        sa.UniqueConstraint(
            "id", "company_id", "branch_id", name="uq_shifts_id_company_id_branch_id"
        ),
    )
    op.create_index(
        "ix_shifts_branch_id_active", "shifts", ["branch_id", "is_active"], unique=False
    )
    op.create_index(
        "uq_shifts_branch_id_code_nonempty",
        "shifts",
        ["branch_id", "code"],
        unique=True,
        postgresql_where=sa.text("code IS NOT NULL AND btrim(code) <> ''"),
    )
    op.create_table(
        "attendance_audit_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("attendance_date", sa.Date(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("actor_app_user_id", sa.UUID(), nullable=False),
        sa.Column("old_value", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("new_value", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_attendance_audit_log_actor_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_attendance_audit_log_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_attendance_audit_log_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_attendance_audit_log_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_audit_log")),
    )
    op.create_index(
        "ix_attendance_audit_log_employee_id_date",
        "attendance_audit_log",
        ["employee_id", "attendance_date"],
        unique=False,
    )
    op.create_table(
        "attendance_records",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("shift_id", sa.UUID(), nullable=True),
        sa.Column("clock_in_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("clock_out_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "total_hours",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'ABSENT'"), nullable=False),
        sa.Column("late_minutes", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "early_departure_minutes", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "overtime_hours",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("overtime_type", sa.Text(), nullable=True),
        sa.Column(
            "overtime_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("overtime_approved_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "overtime_approved", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "worked_on_rest_day", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "rest_day_substitute", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "missing_clock_out", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("is_ramadan_day", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "absence_deduction",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "late_deduction",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("period_closed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("resolved_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("resolution_type", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("resolution_notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "overtime_type IS NULL OR overtime_type IN ('STANDARD', 'REST_DAY_NO_SUB', "
            "'REST_DAY_WITH_SUB', 'NIGHT_SHIFT')",
            name=op.f("ck_attendance_records_overtime_type"),
        ),
        sa.CheckConstraint(
            "resolution_type = '' OR resolved_by_app_user_id IS NOT NULL",
            name=op.f("ck_attendance_records_resolution_actor"),
        ),
        sa.CheckConstraint(
            "resolution_type IN ('', 'LEAVE_LINKED', 'UNAUTHORISED', 'WFH')",
            name=op.f("ck_attendance_records_resolution_type"),
        ),
        sa.CheckConstraint(
            "status IN ('PRESENT', 'ABSENT', 'ON_LEAVE', 'PUBLIC_HOLIDAY', 'WEEKEND', 'LATE', "
            "'EARLY_DEPARTURE', 'HALF_DAY', 'OVERTIME', 'UNEXPLAINED_ABSENCE', 'PRESENT_REMOTE', "
            "'MISSING_CLOCK_OUT')",
            name=op.f("ck_attendance_records_status"),
        ),
        sa.CheckConstraint(
            "NOT overtime_approved OR overtime_approved_by_app_user_id IS NOT NULL",
            name=op.f("ck_attendance_records_overtime_actor"),
        ),
        sa.CheckConstraint(
            "absence_deduction >= 0", name=op.f("ck_attendance_records_absence_deduction")
        ),
        sa.CheckConstraint(
            "late_deduction >= 0", name=op.f("ck_attendance_records_late_deduction")
        ),
        sa.CheckConstraint(
            "overtime_amount >= 0", name=op.f("ck_attendance_records_overtime_amount")
        ),
        sa.CheckConstraint(
            "total_hours >= 0 AND late_minutes >= 0 AND early_departure_minutes >= 0 "
            "AND overtime_hours >= 0",
            name=op.f("ck_attendance_records_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_attendance_records_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_attendance_records_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_attendance_records_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["overtime_approved_by_app_user_id"],
            ["app_users.id"],
            name="fk_attendance_records_ot_approved_by_app_users",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_attendance_records_resolved_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id", "company_id", "branch_id"],
            ["shifts.id", "shifts.company_id", "shifts.branch_id"],
            name=op.f("fk_attendance_records_shift_id_shifts"),
            ondelete="SET NULL (shift_id)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_records")),
        sa.UniqueConstraint("employee_id", "date", name="uq_attendance_records_employee_id_date"),
    )
    op.create_index(
        "ix_attendance_records_branch_id_date",
        "attendance_records",
        ["branch_id", "date"],
        unique=False,
    )
    op.create_index(
        "ix_attendance_records_employee_id_date",
        "attendance_records",
        ["employee_id", "date"],
        unique=False,
    )
    op.create_index("ix_attendance_records_status", "attendance_records", ["status"], unique=False)
    op.create_table(
        "biometric_mappings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("badge_no", sa.Text(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("device_name", sa.Text(), server_default=sa.text("'Default'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_biometric_mappings_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_biometric_mappings_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_biometric_mappings_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_biometric_mappings")),
        sa.UniqueConstraint(
            "branch_id", "badge_no", name="uq_biometric_mappings_branch_id_badge_no"
        ),
    )
    op.create_index(
        "ix_biometric_mappings_employee_id", "biometric_mappings", ["employee_id"], unique=False
    )
    op.create_table(
        "regularisation_requests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("attendance_date", sa.Date(), nullable=False),
        sa.Column("correct_clock_in", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correct_clock_out", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'Pending'"), nullable=False),
        sa.Column("approved_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("original_clock_in", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_clock_out", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'Rejected' OR btrim(rejection_reason) <> ''",
            name=op.f("ck_regularisation_requests_rejection_fields"),
        ),
        sa.CheckConstraint(
            "status = 'Pending' OR (approved_by_app_user_id IS NOT NULL "
            "AND approved_at IS NOT NULL)",
            name=op.f("ck_regularisation_requests_decision_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('Pending', 'Approved', 'Rejected')",
            name=op.f("ck_regularisation_requests_status"),
        ),
        sa.CheckConstraint(
            "correct_clock_out > correct_clock_in",
            name=op.f("ck_regularisation_requests_clock_order"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_regularisation_requests_approved_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_regularisation_requests_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_regularisation_requests_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_regularisation_requests_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regularisation_requests")),
        sa.UniqueConstraint(
            "id",
            "company_id",
            "branch_id",
            name="uq_regularisation_requests_id_company_id_branch_id",
        ),
        sa.UniqueConstraint(
            "id",
            "employee_id",
            "company_id",
            "branch_id",
            name="uq_regularisation_requests_id_employee_id_company_id_branch_id",
        ),
    )
    op.create_index(
        "ix_regularisation_requests_employee_id_attendance_date",
        "regularisation_requests",
        ["employee_id", "attendance_date"],
        unique=False,
    )
    op.create_index(
        "ix_regularisation_requests_status", "regularisation_requests", ["status"], unique=False
    )
    op.create_table(
        "roster_assignments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("shift_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("planned_hours", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("actual_hours", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column(
            "co_hours",
            sa.Numeric(precision=4, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(planned_hours IS NULL OR planned_hours >= 0) "
            "AND (actual_hours IS NULL OR actual_hours >= 0) AND co_hours >= 0",
            name=op.f("ck_roster_assignments_hours"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_roster_assignments_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_roster_assignments_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_roster_assignments_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id", "company_id", "branch_id"],
            ["shifts.id", "shifts.company_id", "shifts.branch_id"],
            name=op.f("fk_roster_assignments_shift_id_shifts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roster_assignments")),
        sa.UniqueConstraint("employee_id", "date", name="uq_roster_assignments_employee_id_date"),
    )
    op.create_index(
        "ix_roster_assignments_branch_id", "roster_assignments", ["branch_id"], unique=False
    )
    op.create_index("ix_roster_assignments_date", "roster_assignments", ["date"], unique=False)
    op.create_index(
        "ix_roster_assignments_employee_id", "roster_assignments", ["employee_id"], unique=False
    )
    op.create_table(
        "shift_assignments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("shift_id", sa.UUID(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_shift_assignments_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_shift_assignments_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_shift_assignments_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_shift_assignments_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shift_id", "company_id", "branch_id"],
            ["shifts.id", "shifts.company_id", "shifts.branch_id"],
            name=op.f("fk_shift_assignments_shift_id_shifts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shift_assignments")),
    )
    op.create_index(
        "ix_shift_assignments_employee_id_effective_from",
        "shift_assignments",
        ["employee_id", sa.literal_column("effective_from DESC")],
        unique=False,
    )
    op.create_table(
        "shift_swap_requests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("requester_employee_id", sa.UUID(), nullable=False),
        sa.Column("target_employee_id", sa.UUID(), nullable=False),
        sa.Column("requester_date", sa.Date(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("admin_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_approved_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'approved' OR (admin_approved_by_app_user_id IS NOT NULL "
            "AND admin_approved_at IS NOT NULL)",
            name=op.f("ck_shift_swap_requests_approved_fields"),
        ),
        sa.CheckConstraint(
            "status <> 'rejected' OR (admin_approved_by_app_user_id IS NOT NULL "
            "AND admin_approved_at IS NOT NULL AND btrim(rejection_reason) <> '')",
            name=op.f("ck_shift_swap_requests_rejected_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'cancelled')",
            name=op.f("ck_shift_swap_requests_status"),
        ),
        sa.CheckConstraint(
            "requester_employee_id <> target_employee_id",
            name=op.f("ck_shift_swap_requests_distinct_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["admin_approved_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_shift_swap_requests_admin_approved_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_shift_swap_requests_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_shift_swap_requests_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requester_employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name="fk_shift_swap_requests_requester_employee_id_employees",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name="fk_shift_swap_requests_target_employee_id_employees",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shift_swap_requests")),
    )
    op.create_index(
        "ix_shift_swap_requests_branch_id", "shift_swap_requests", ["branch_id"], unique=False
    )
    op.create_index(
        "ix_shift_swap_requests_requester_employee_id",
        "shift_swap_requests",
        ["requester_employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_shift_swap_requests_status", "shift_swap_requests", ["status"], unique=False
    )
    op.create_table(
        "clock_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("method", sa.Text(), server_default=sa.text("'WEB'"), nullable=False),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("gps_lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("gps_lng", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("entered_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("is_superseded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('CLOCK_IN', 'CLOCK_OUT')", name=op.f("ck_clock_events_event_type")
        ),
        sa.CheckConstraint(
            "method IN ('WEB', 'MOBILE', 'MANUAL', 'BIOMETRIC', 'EMPLOYEE_APP')",
            name=op.f("ck_clock_events_method"),
        ),
        sa.CheckConstraint(
            "gps_lat IS NULL OR gps_lat BETWEEN -90 AND 90", name=op.f("ck_clock_events_latitude")
        ),
        sa.CheckConstraint(
            "gps_lng IS NULL OR gps_lng BETWEEN -180 AND 180",
            name=op.f("ck_clock_events_longitude"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_clock_events_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_clock_events_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_clock_events_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entered_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_clock_events_entered_by_app_user_id_app_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by", "employee_id", "company_id", "branch_id"],
            [
                "regularisation_requests.id",
                "regularisation_requests.employee_id",
                "regularisation_requests.company_id",
                "regularisation_requests.branch_id",
            ],
            name="fk_clock_events_superseded_by_regularisation_requests",
            ondelete="SET NULL (superseded_by)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clock_events")),
    )
    op.create_index("ix_clock_events_branch_id", "clock_events", ["branch_id"], unique=False)
    op.create_index(
        "ix_clock_events_employee_id_event_time",
        "clock_events",
        ["employee_id", "event_time"],
        unique=False,
    )
    op.create_index("ix_clock_events_event_time", "clock_events", ["event_time"], unique=False)
    op.create_foreign_key(
        "fk_employees_shift_id_shifts",
        "employees",
        "shifts",
        ["shift_id", "company_id", "branch_id"],
        ["id", "company_id", "branch_id"],
        ondelete="SET NULL (shift_id)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_employees_shift_id_shifts", "employees", type_="foreignkey")
    op.drop_index("ix_clock_events_event_time", table_name="clock_events")
    op.drop_index("ix_clock_events_employee_id_event_time", table_name="clock_events")
    op.drop_index("ix_clock_events_branch_id", table_name="clock_events")
    op.drop_table("clock_events")
    op.drop_index("ix_shift_swap_requests_status", table_name="shift_swap_requests")
    op.drop_index("ix_shift_swap_requests_requester_employee_id", table_name="shift_swap_requests")
    op.drop_index("ix_shift_swap_requests_branch_id", table_name="shift_swap_requests")
    op.drop_table("shift_swap_requests")
    op.drop_index("ix_shift_assignments_employee_id_effective_from", table_name="shift_assignments")
    op.drop_table("shift_assignments")
    op.drop_index("ix_roster_assignments_employee_id", table_name="roster_assignments")
    op.drop_index("ix_roster_assignments_date", table_name="roster_assignments")
    op.drop_index("ix_roster_assignments_branch_id", table_name="roster_assignments")
    op.drop_table("roster_assignments")
    op.drop_index("ix_regularisation_requests_status", table_name="regularisation_requests")
    op.drop_index(
        "ix_regularisation_requests_employee_id_attendance_date",
        table_name="regularisation_requests",
    )
    op.drop_table("regularisation_requests")
    op.drop_index("ix_biometric_mappings_employee_id", table_name="biometric_mappings")
    op.drop_table("biometric_mappings")
    op.drop_index("ix_attendance_records_status", table_name="attendance_records")
    op.drop_index("ix_attendance_records_employee_id_date", table_name="attendance_records")
    op.drop_index("ix_attendance_records_branch_id_date", table_name="attendance_records")
    op.drop_table("attendance_records")
    op.drop_index("ix_attendance_audit_log_employee_id_date", table_name="attendance_audit_log")
    op.drop_table("attendance_audit_log")
    op.drop_index(
        "uq_shifts_branch_id_code_nonempty",
        table_name="shifts",
        postgresql_where=sa.text("code IS NOT NULL AND btrim(code) <> ''"),
    )
    op.drop_index("ix_shifts_branch_id_active", table_name="shifts")
    op.drop_table("shifts")
    op.drop_index("ix_attendance_settings_company_id_branch_id", table_name="attendance_settings")
    op.drop_table("attendance_settings")
    op.drop_index("ix_attendance_periods_branch_id_period", table_name="attendance_periods")
    op.drop_table("attendance_periods")
    # ### end Alembic commands ###
