"""add records benefits clinical schema

Revision ID: 7d3e5a1f6c54
Revises: 6c2d4f0e5b43
Created: 2026-09-02 08:41:15.734835
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7d3e5a1f6c54"
down_revision: str | Sequence[str] | None = "6c2d4f0e5b43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appraisal_cycles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("review_from", sa.Date(), nullable=False),
        sa.Column("review_to", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("closed_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'closed' OR (closed_by_app_user_id IS NOT NULL AND closed_at IS NOT NULL)",
            name=op.f("ck_appraisal_cycles_closed_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'closed')", name=op.f("ck_appraisal_cycles_status")
        ),
        sa.CheckConstraint("review_to >= review_from", name=op.f("ck_appraisal_cycles_dates")),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_appraisal_cycles_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_appraisal_cycles_closed_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_appraisal_cycles_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appraisal_cycles")),
        sa.UniqueConstraint("branch_id", "name", name="uq_appraisal_cycles_branch_id_name"),
        sa.UniqueConstraint(
            "id", "company_id", "branch_id", name="uq_appraisal_cycles_id_company_id_branch_id"
        ),
    )
    op.create_index(
        "ix_appraisal_cycles_branch_id_status",
        "appraisal_cycles",
        ["branch_id", "status"],
        unique=False,
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("asset_code", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("category", sa.Text(), server_default=sa.text("'other'"), nullable=False),
        sa.Column("brand", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("model", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("serial_number", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("purchase_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'available'"), nullable=False),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('available', 'assigned', 'under_repair', 'retired', 'lost')",
            name=op.f("ck_assets_status"),
        ),
        sa.CheckConstraint(
            "purchase_cost IS NULL OR purchase_cost >= 0", name=op.f("ck_assets_purchase_cost")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_assets_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_assets_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint(
            "id", "company_id", "branch_id", name="uq_assets_id_company_id_branch_id"
        ),
    )
    op.create_index("ix_assets_branch_id_status", "assets", ["branch_id", "status"], unique=False)
    op.create_index(
        "uq_assets_branch_id_asset_code_nonempty",
        "assets",
        ["branch_id", "asset_code"],
        unique=True,
        postgresql_where=sa.text("btrim(asset_code) <> ''"),
    )
    op.create_table(
        "insurance_policies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("insurer_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("policy_number", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("tier_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "annual_premium",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("renewal_date", sa.Date(), nullable=True),
        sa.Column("broker_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("broker_contact", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "annual_premium >= 0", name=op.f("ck_insurance_policies_annual_premium")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_insurance_policies_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_insurance_policies_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance_policies")),
        sa.UniqueConstraint(
            "id", "company_id", "branch_id", name="uq_insurance_policies_id_company_id_branch_id"
        ),
    )
    op.create_index(
        "ix_insurance_policies_branch_id_renewal_date",
        "insurance_policies",
        ["branch_id", "renewal_date"],
        unique=False,
    )
    op.create_table(
        "offboarding_task_templates",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("task_name", sa.Text(), nullable=False),
        sa.Column("default_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_offboarding_task_templates_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_offboarding_task_templates_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offboarding_task_templates")),
        sa.UniqueConstraint(
            "branch_id", "task_name", name="uq_offboarding_task_templates_branch_id_task_name"
        ),
    )
    op.create_index(
        "ix_offboarding_task_templates_branch_id",
        "offboarding_task_templates",
        ["branch_id"],
        unique=False,
    )
    op.create_table(
        "appraisals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("overall_rating", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("self_rating", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("reviewer_comments", sa.Text(), nullable=True),
        sa.Column("development_plan", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = 'pending' OR (reviewed_by_app_user_id IS NOT NULL "
            "AND reviewed_at IS NOT NULL)",
            name=op.f("ck_appraisals_review_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'reviewed', 'calibrated')", name=op.f("ck_appraisals_status")
        ),
        sa.CheckConstraint(
            "overall_rating IS NULL OR overall_rating BETWEEN 1 AND 5",
            name=op.f("ck_appraisals_overall_rating"),
        ),
        sa.CheckConstraint(
            "self_rating IS NULL OR self_rating BETWEEN 1 AND 5",
            name=op.f("ck_appraisals_self_rating"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_appraisals_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_appraisals_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id", "company_id", "branch_id"],
            ["appraisal_cycles.id", "appraisal_cycles.company_id", "appraisal_cycles.branch_id"],
            name=op.f("fk_appraisals_cycle_id_appraisal_cycles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_appraisals_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_appraisals_reviewed_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appraisals")),
        sa.UniqueConstraint("cycle_id", "employee_id", name="uq_appraisals_cycle_id_employee_id"),
        sa.UniqueConstraint(
            "id", "company_id", "branch_id", name="uq_appraisals_id_company_id_branch_id"
        ),
    )
    op.create_index(
        "ix_appraisals_branch_id_status", "appraisals", ["branch_id", "status"], unique=False
    )
    op.create_index("ix_appraisals_cycle_id", "appraisals", ["cycle_id"], unique=False)
    op.create_index("ix_appraisals_employee_id", "appraisals", ["employee_id"], unique=False)
    op.create_table(
        "asset_assignments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
        sa.Column("return_date", sa.Date(), nullable=True),
        sa.Column(
            "condition_at_handover", sa.Text(), server_default=sa.text("'good'"), nullable=False
        ),
        sa.Column("condition_at_return", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("assigned_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "return_date IS NULL OR return_date >= assigned_date",
            name=op.f("ck_asset_assignments_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_id", "company_id", "branch_id"],
            ["assets.id", "assets.company_id", "assets.branch_id"],
            name=op.f("fk_asset_assignments_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_asset_assignments_assigned_by_app_user_id_app_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_asset_assignments_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_asset_assignments_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_asset_assignments_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_assignments")),
    )
    op.create_index(
        "ix_asset_assignments_asset_id", "asset_assignments", ["asset_id"], unique=False
    )
    op.create_index(
        "ix_asset_assignments_employee_id", "asset_assignments", ["employee_id"], unique=False
    )
    op.create_index(
        "uq_asset_assignments_open_asset",
        "asset_assignments",
        ["asset_id"],
        unique=True,
        postgresql_where=sa.text("return_date IS NULL"),
    )
    op.create_table(
        "certifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("certification_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("issuing_body", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("certificate_no", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("certificate_url", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("storage_path", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("file_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'verified'"), nullable=False),
        sa.Column("reviewed_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'rejected' OR btrim(notes) <> ''",
            name=op.f("ck_certifications_rejection_fields"),
        ),
        sa.CheckConstraint(
            "status = 'pending_review' OR (reviewed_by_app_user_id IS NOT NULL "
            "AND reviewed_at IS NOT NULL)",
            name=op.f("ck_certifications_review_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('pending_review', 'verified', 'rejected')",
            name=op.f("ck_certifications_status"),
        ),
        sa.CheckConstraint(
            "expiry_date IS NULL OR issued_date IS NULL OR expiry_date >= issued_date",
            name=op.f("ck_certifications_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_certifications_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_certifications_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_certifications_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_certifications_reviewed_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certifications")),
    )
    op.create_index(
        "ix_certifications_branch_id_expiry_date",
        "certifications",
        ["branch_id", "expiry_date"],
        unique=False,
    )
    op.create_index(
        "ix_certifications_employee_id", "certifications", ["employee_id"], unique=False
    )
    op.create_table(
        "cme_requirements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "required_hours",
            sa.Numeric(precision=6, scale=1),
            server_default=sa.text("25"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("required_hours >= 0", name=op.f("ck_cme_requirements_required_hours")),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_cme_requirements_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_cme_requirements_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_cme_requirements_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cme_requirements")),
        sa.UniqueConstraint("employee_id", "year", name="uq_cme_requirements_employee_id_year"),
    )
    op.create_index(
        "ix_cme_requirements_employee_id", "cme_requirements", ["employee_id"], unique=False
    )
    op.create_index("ix_cme_requirements_year", "cme_requirements", ["year"], unique=False)
    op.create_table(
        "employee_contracts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("contract_type", sa.Text(), server_default=sa.text("'Limited'"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "renewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("renewed_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), server_default=sa.text("'new'"), nullable=False),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('new', 'renewed', 'converted', 'not_renewed')",
            name=op.f("ck_employee_contracts_action"),
        ),
        sa.CheckConstraint(
            "contract_type IN ('Limited', 'Unlimited')",
            name=op.f("ck_employee_contracts_contract_type"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_employee_contracts_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_employee_contracts_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_employee_contracts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_employee_contracts_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["renewed_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_employee_contracts_renewed_by_app_user_id_app_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_contracts")),
    )
    op.create_index(
        "ix_employee_contracts_branch_id_end_date",
        "employee_contracts",
        ["branch_id", "end_date"],
        unique=False,
    )
    op.create_index(
        "ix_employee_contracts_employee_id", "employee_contracts", ["employee_id"], unique=False
    )
    op.create_table(
        "employee_documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.Text(), nullable=False),
        sa.Column("document_number", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_size", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("storage_path", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'verified'"), nullable=False),
        sa.Column("rejection_reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("submitted_by", sa.Text(), server_default=sa.text("'hr'"), nullable=False),
        sa.Column("reviewed_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'rejected' OR btrim(rejection_reason) <> ''",
            name=op.f("ck_employee_documents_rejection_fields"),
        ),
        sa.CheckConstraint(
            "status = 'pending_verification' OR (reviewed_by_app_user_id IS NOT NULL "
            "AND reviewed_at IS NOT NULL)",
            name=op.f("ck_employee_documents_review_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('pending_verification', 'verified', 'rejected')",
            name=op.f("ck_employee_documents_status"),
        ),
        sa.CheckConstraint(
            "submitted_by IN ('hr', 'employee')", name=op.f("ck_employee_documents_submitted_by")
        ),
        sa.CheckConstraint("file_size >= 0", name=op.f("ck_employee_documents_file_size")),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_employee_documents_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_employee_documents_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_employee_documents_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_employee_documents_reviewed_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_documents")),
    )
    op.create_index(
        "ix_employee_documents_branch_id_expiry_date",
        "employee_documents",
        ["branch_id", "expiry_date"],
        unique=False,
    )
    op.create_index(
        "ix_employee_documents_employee_id", "employee_documents", ["employee_id"], unique=False
    )
    op.create_table(
        "employee_insurance",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=True),
        sa.Column("member_id", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("card_number", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("tier_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expiry_date IS NULL OR effective_date IS NULL OR expiry_date >= effective_date",
            name=op.f("ck_employee_insurance_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_employee_insurance_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_employee_insurance_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_employee_insurance_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id", "company_id", "branch_id"],
            [
                "insurance_policies.id",
                "insurance_policies.company_id",
                "insurance_policies.branch_id",
            ],
            name=op.f("fk_employee_insurance_policy_id_insurance_policies"),
            ondelete="SET NULL (policy_id)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_insurance")),
        sa.UniqueConstraint("employee_id", name="uq_employee_insurance_employee_id"),
    )
    op.create_index(
        "ix_employee_insurance_branch_id_expiry_date",
        "employee_insurance",
        ["branch_id", "expiry_date"],
        unique=False,
    )
    op.create_table(
        "incident_reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("incident_date", sa.Date(), nullable=False),
        sa.Column("incident_time", sa.Time(), nullable=True),
        sa.Column("location", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("department", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("incident_type", sa.Text(), server_default=sa.text("'other'"), nullable=False),
        sa.Column("severity", sa.Text(), server_default=sa.text("'low'"), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("reported_by_id", sa.UUID(), nullable=True),
        sa.Column("involved_emp_id", sa.UUID(), nullable=True),
        sa.Column("immediate_action", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("root_cause", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("corrective_action", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("closed_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "incident_type IN ('patient_safety', 'medication_error', 'injury', 'needlestick', "
            "'infection', 'equipment', 'near_miss', 'workplace', 'other')",
            name=op.f("ck_incident_reports_incident_type"),
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'moderate', 'high', 'critical')",
            name=op.f("ck_incident_reports_severity"),
        ),
        sa.CheckConstraint(
            "status <> 'closed' OR (closed_by_app_user_id IS NOT NULL AND closed_date IS NOT NULL)",
            name=op.f("ck_incident_reports_closed_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'investigating', 'closed')", name=op.f("ck_incident_reports_status")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_incident_reports_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_incident_reports_closed_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_incident_reports_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["involved_emp_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name="fk_incident_reports_involved_emp_id_employees",
            ondelete="SET NULL (involved_emp_id)",
        ),
        sa.ForeignKeyConstraint(
            ["reported_by_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name="fk_incident_reports_reported_by_id_employees",
            ondelete="SET NULL (reported_by_id)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_reports")),
    )
    op.create_index(
        "ix_incident_reports_branch_id_incident_date",
        "incident_reports",
        ["branch_id", "incident_date"],
        unique=False,
    )
    op.create_index(
        "ix_incident_reports_department", "incident_reports", ["department"], unique=False
    )
    op.create_index("ix_incident_reports_severity", "incident_reports", ["severity"], unique=False)
    op.create_index("ix_incident_reports_status", "incident_reports", ["status"], unique=False)
    op.create_table(
        "insurance_dependants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("relationship", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("card_number", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_insurance_dependants_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_insurance_dependants_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_insurance_dependants_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance_dependants")),
    )
    op.create_index(
        "ix_insurance_dependants_employee_id", "insurance_dependants", ["employee_id"], unique=False
    )
    op.create_table(
        "letter_requests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("request_kind", sa.Text(), server_default=sa.text("'letter'"), nullable=False),
        sa.Column("letter_type", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("rejection_reason", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actioned_by_app_user_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "request_kind <> 'custom' OR (char_length(btrim(letter_type)) BETWEEN 3 AND 120 "
            "AND char_length(btrim(purpose)) BETWEEN 5 AND 2000)",
            name=op.f("ck_letter_requests_custom_lengths"),
        ),
        sa.CheckConstraint(
            "request_kind IN ('letter', 'custom')", name=op.f("ck_letter_requests_request_kind")
        ),
        sa.CheckConstraint(
            "status <> 'completed' OR (actioned_by_app_user_id IS NOT NULL "
            "AND actioned_at IS NOT NULL AND completed_at IS NOT NULL)",
            name=op.f("ck_letter_requests_completed_fields"),
        ),
        sa.CheckConstraint(
            "status <> 'rejected' OR (actioned_by_app_user_id IS NOT NULL "
            "AND actioned_at IS NOT NULL AND btrim(rejection_reason) <> '')",
            name=op.f("ck_letter_requests_rejected_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'rejected')", name=op.f("ck_letter_requests_status")
        ),
        sa.ForeignKeyConstraint(
            ["actioned_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_letter_requests_actioned_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_letter_requests_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_letter_requests_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_letter_requests_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_letter_requests")),
    )
    op.create_index(
        "ix_letter_requests_branch_id_status",
        "letter_requests",
        ["branch_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_letter_requests_employee_id", "letter_requests", ["employee_id"], unique=False
    )
    op.create_table(
        "offboarding_checklists",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'in_progress'"), nullable=False),
        sa.Column(
            "visa_cancellation_status",
            sa.Text(),
            server_default=sa.text("'not_started'"),
            nullable=False,
        ),
        sa.Column("visa_cancellation_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_app_user_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status <> 'completed' OR (completed_by_app_user_id IS NOT NULL "
            "AND completed_at IS NOT NULL)",
            name=op.f("ck_offboarding_checklists_completed_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'completed')", name=op.f("ck_offboarding_checklists_status")
        ),
        sa.CheckConstraint(
            "visa_cancellation_status IN ('not_started', 'initiated', 'submitted_gdrfa', "
            "'cancelled')",
            name=op.f("ck_offboarding_checklists_visa_cancellation_status"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_offboarding_checklists_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_offboarding_checklists_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_offboarding_checklists_completed_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_offboarding_checklists_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offboarding_checklists")),
        sa.UniqueConstraint("employee_id", name="uq_offboarding_checklists_employee_id"),
        sa.UniqueConstraint(
            "id",
            "company_id",
            "branch_id",
            name="uq_offboarding_checklists_id_company_id_branch_id",
        ),
    )
    op.create_index(
        "ix_offboarding_checklists_branch_id_status",
        "offboarding_checklists",
        ["branch_id", "status"],
        unique=False,
    )
    op.create_table(
        "training_records",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("training_title", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("training_type", sa.Text(), server_default=sa.text("'external'"), nullable=False),
        sa.Column("provider", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("duration_hours", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "cost", sa.Numeric(precision=12, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'planned'"), nullable=False),
        sa.Column("score", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("certificate_url", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("storage_path", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("file_name", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("is_cme", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'completed' OR end_date IS NOT NULL",
            name=op.f("ck_training_records_completed_fields"),
        ),
        sa.CheckConstraint(
            "status IN ('planned', 'in_progress', 'completed', 'cancelled')",
            name=op.f("ck_training_records_status"),
        ),
        sa.CheckConstraint("cost >= 0", name=op.f("ck_training_records_cost")),
        sa.CheckConstraint(
            "duration_hours IS NULL OR duration_hours >= 0",
            name=op.f("ck_training_records_duration_hours"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_training_records_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_training_records_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_training_records_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id", "company_id", "branch_id"],
            ["employees.id", "employees.company_id", "employees.branch_id"],
            name=op.f("fk_training_records_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_records")),
    )
    op.create_index(
        "ix_training_records_branch_id_status",
        "training_records",
        ["branch_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_training_records_employee_id", "training_records", ["employee_id"], unique=False
    )
    op.create_table(
        "appraisal_sections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("appraisal_id", sa.UUID(), nullable=False),
        sa.Column("section_name", sa.Text(), nullable=False),
        sa.Column(
            "weight",
            sa.Numeric(precision=4, scale=2),
            server_default=sa.text("1.0"),
            nullable=False,
        ),
        sa.Column("rating", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("self_rating", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 1 AND 5", name=op.f("ck_appraisal_sections_rating")
        ),
        sa.CheckConstraint(
            "self_rating IS NULL OR self_rating BETWEEN 1 AND 5",
            name=op.f("ck_appraisal_sections_self_rating"),
        ),
        sa.CheckConstraint("weight > 0", name=op.f("ck_appraisal_sections_weight")),
        sa.ForeignKeyConstraint(
            ["appraisal_id", "company_id", "branch_id"],
            ["appraisals.id", "appraisals.company_id", "appraisals.branch_id"],
            name=op.f("fk_appraisal_sections_appraisal_id_appraisals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_appraisal_sections_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_appraisal_sections_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appraisal_sections")),
        sa.UniqueConstraint(
            "appraisal_id", "section_name", name="uq_appraisal_sections_appraisal_id_section_name"
        ),
    )
    op.create_index(
        "ix_appraisal_sections_appraisal_id_sort_order",
        "appraisal_sections",
        ["appraisal_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        "ix_appraisal_sections_company_id_branch_id",
        "appraisal_sections",
        ["company_id", "branch_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column("created_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("recipient_app_user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("body", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("related_entity_type", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("related_entity_id", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_notifications_branch_id_branches"),
            ondelete="SET NULL (branch_id)",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_notifications_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_app_user_id", "company_id"],
            ["user_profiles.app_user_id", "user_profiles.company_id"],
            name="fk_notifications_created_by_app_user_id_user_profiles",
            ondelete="SET NULL (created_by_app_user_id)",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_app_user_id", "company_id"],
            ["user_profiles.app_user_id", "user_profiles.company_id"],
            name="fk_notifications_recipient_app_user_id_user_profiles",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint(
            "company_id",
            "recipient_app_user_id",
            "type",
            "related_entity_type",
            "related_entity_id",
            name="uq_notifications_dedup",
        ),
    )
    op.create_index(
        "ix_notifications_company_id_branch_id",
        "notifications",
        ["company_id", "branch_id"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_recipient_app_user_id",
        "notifications",
        ["recipient_app_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_unread",
        "notifications",
        ["recipient_app_user_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_table(
        "offboarding_tasks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("checklist_id", sa.UUID(), nullable=False),
        sa.Column("task_name", sa.Text(), nullable=False),
        sa.Column("completed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_app_user_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT completed OR (completed_by_app_user_id IS NOT NULL AND completed_at IS NOT NULL)",
            name=op.f("ck_offboarding_tasks_completed_fields"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id", "company_id"],
            ["branches.id", "branches.company_id"],
            name=op.f("fk_offboarding_tasks_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["checklist_id", "company_id", "branch_id"],
            [
                "offboarding_checklists.id",
                "offboarding_checklists.company_id",
                "offboarding_checklists.branch_id",
            ],
            name=op.f("fk_offboarding_tasks_checklist_id_offboarding_checklists"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_offboarding_tasks_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_app_user_id"],
            ["app_users.id"],
            name=op.f("fk_offboarding_tasks_completed_by_app_user_id_app_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offboarding_tasks")),
    )
    op.create_index(
        "ix_offboarding_tasks_checklist_id_sort_order",
        "offboarding_tasks",
        ["checklist_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        "ix_offboarding_tasks_company_id_branch_id",
        "offboarding_tasks",
        ["company_id", "branch_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_offboarding_tasks_company_id_branch_id", table_name="offboarding_tasks")
    op.drop_index("ix_offboarding_tasks_checklist_id_sort_order", table_name="offboarding_tasks")
    op.drop_table("offboarding_tasks")
    op.drop_index(
        "ix_notifications_unread",
        table_name="notifications",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_index("ix_notifications_recipient_app_user_id", table_name="notifications")
    op.drop_index("ix_notifications_company_id_branch_id", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_appraisal_sections_company_id_branch_id", table_name="appraisal_sections")
    op.drop_index("ix_appraisal_sections_appraisal_id_sort_order", table_name="appraisal_sections")
    op.drop_table("appraisal_sections")
    op.drop_index("ix_training_records_employee_id", table_name="training_records")
    op.drop_index("ix_training_records_branch_id_status", table_name="training_records")
    op.drop_table("training_records")
    op.drop_index("ix_offboarding_checklists_branch_id_status", table_name="offboarding_checklists")
    op.drop_table("offboarding_checklists")
    op.drop_index("ix_letter_requests_employee_id", table_name="letter_requests")
    op.drop_index("ix_letter_requests_branch_id_status", table_name="letter_requests")
    op.drop_table("letter_requests")
    op.drop_index("ix_insurance_dependants_employee_id", table_name="insurance_dependants")
    op.drop_table("insurance_dependants")
    op.drop_index("ix_incident_reports_status", table_name="incident_reports")
    op.drop_index("ix_incident_reports_severity", table_name="incident_reports")
    op.drop_index("ix_incident_reports_department", table_name="incident_reports")
    op.drop_index("ix_incident_reports_branch_id_incident_date", table_name="incident_reports")
    op.drop_table("incident_reports")
    op.drop_index("ix_employee_insurance_branch_id_expiry_date", table_name="employee_insurance")
    op.drop_table("employee_insurance")
    op.drop_index("ix_employee_documents_employee_id", table_name="employee_documents")
    op.drop_index("ix_employee_documents_branch_id_expiry_date", table_name="employee_documents")
    op.drop_table("employee_documents")
    op.drop_index("ix_employee_contracts_employee_id", table_name="employee_contracts")
    op.drop_index("ix_employee_contracts_branch_id_end_date", table_name="employee_contracts")
    op.drop_table("employee_contracts")
    op.drop_index("ix_cme_requirements_year", table_name="cme_requirements")
    op.drop_index("ix_cme_requirements_employee_id", table_name="cme_requirements")
    op.drop_table("cme_requirements")
    op.drop_index("ix_certifications_employee_id", table_name="certifications")
    op.drop_index("ix_certifications_branch_id_expiry_date", table_name="certifications")
    op.drop_table("certifications")
    op.drop_index(
        "uq_asset_assignments_open_asset",
        table_name="asset_assignments",
        postgresql_where=sa.text("return_date IS NULL"),
    )
    op.drop_index("ix_asset_assignments_employee_id", table_name="asset_assignments")
    op.drop_index("ix_asset_assignments_asset_id", table_name="asset_assignments")
    op.drop_table("asset_assignments")
    op.drop_index("ix_appraisals_employee_id", table_name="appraisals")
    op.drop_index("ix_appraisals_cycle_id", table_name="appraisals")
    op.drop_index("ix_appraisals_branch_id_status", table_name="appraisals")
    op.drop_table("appraisals")
    op.drop_index(
        "ix_offboarding_task_templates_branch_id", table_name="offboarding_task_templates"
    )
    op.drop_table("offboarding_task_templates")
    op.drop_index("ix_insurance_policies_branch_id_renewal_date", table_name="insurance_policies")
    op.drop_table("insurance_policies")
    op.drop_index(
        "uq_assets_branch_id_asset_code_nonempty",
        table_name="assets",
        postgresql_where=sa.text("btrim(asset_code) <> ''"),
    )
    op.drop_index("ix_assets_branch_id_status", table_name="assets")
    op.drop_table("assets")
    op.drop_index("ix_appraisal_cycles_branch_id_status", table_name="appraisal_cycles")
    op.drop_table("appraisal_cycles")
    # ### end Alembic commands ###
