/**
 * EndOfServiceScreen.jsx — UAE End-of-Service Settlement Calculator
 *
 * When an employee is terminated or resigns, this screen calculates:
 *   1. Gratuity / EOSB (UAE Labour Law Art. 51)
 *   2. Pro-rata final salary for the last partial month
 *   3. Outstanding advance deductions
 *   4. Total net settlement payable
 *
 * Can be opened from the employee profile or payroll module.
 */
import { useState } from 'react';
import { X, Calculator, Download } from 'lucide-react';
import { calculateEndOfService } from '../utils/gratuityCalculator';
import { formatAED, formatDateUAE } from '../utils/uaeValidators';

export default function EndOfServiceScreen({ employee, onClose }) {
  const today = new Date().toISOString().split('T')[0];

  const [terminationDate, setTerminationDate] = useState(
    employee.terminationDate || today
  );
  const [outstandingAdvances, setOutstandingAdvances] = useState('0');
  const [result, setResult] = useState(null);

  const calculate = () => {
    if (!employee.startDate && !employee.employmentStartDate) {
      alert('Employee start date is not set. Please update the employee profile first.');
      return;
    }
    const settlement = calculateEndOfService(
      employee,
      terminationDate,
      parseFloat(outstandingAdvances) || 0
    );
    setResult(settlement);
  };

  const printSettlement = () => {
    if (!result) return;
    const win = window.open('', '_blank');
    win.document.write(`
      <html><head><title>End of Service Settlement — ${employee.name}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #111; }
        h1 { color: #1a56db; font-size: 22px; }
        h2 { font-size: 16px; color: #374151; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; margin-top: 24px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        td { padding: 8px 12px; border-bottom: 1px solid #f3f4f6; font-size: 14px; }
        td:last-child { text-align: right; font-weight: 600; }
        .total { background: #eff6ff; font-weight: 700; font-size: 16px; }
        .deduct { color: #c81e1e; }
        .footer { margin-top: 40px; font-size: 12px; color: #9ca3af; }
      </style></head><body>
      <h1>End-of-Service Settlement</h1>
      <p><strong>Employee:</strong> ${result.employee}</p>
      <p><strong>Start Date:</strong> ${formatDateUAE(result.startDate)} &nbsp;|&nbsp; <strong>Termination Date:</strong> ${formatDateUAE(result.terminationDate)}</p>
      <p><strong>Years of Service:</strong> ${result.yearsOfService.toFixed(2)} years</p>

      <h2>Final Month Salary (Pro-rata)</h2>
      <table>
        <tr><td>Days Worked in Final Month</td><td>${result.daysWorked} / ${result.daysInMonth} days</td></tr>
        <tr><td>Monthly Total Package</td><td>${formatAED(result.totalMonthly)}</td></tr>
        <tr><td>Pro-rata Final Salary</td><td>${formatAED(result.proRataFinalSalary)}</td></tr>
      </table>

      <h2>Gratuity / EOSB (UAE Labour Law Art. 51)</h2>
      <table>
        <tr><td>Eligible</td><td>${result.gratuity.eligible ? 'Yes' : 'No (< 1 year service)'}</td></tr>
        ${result.gratuity.eligible ? `
        <tr><td>Calculation</td><td>${result.gratuity.breakdown}</td></tr>
        <tr><td>Gratuity (before cap)</td><td>${formatAED(result.gratuity.gratuityRaw)}</td></tr>
        <tr><td>2-Year Cap</td><td>${formatAED(result.gratuity.cap)}</td></tr>
        <tr><td>Gratuity Payable</td><td>${formatAED(result.gratuity.gratuityCapped)}</td></tr>
        ` : ''}
      </table>

      <h2>Settlement Summary</h2>
      <table>
        <tr><td>Pro-rata Final Salary</td><td>${formatAED(result.proRataFinalSalary)}</td></tr>
        <tr><td>Gratuity / EOSB</td><td>${formatAED(result.gratuity.gratuityCapped)}</td></tr>
        <tr><td>Total Gross</td><td>${formatAED(result.totalGross)}</td></tr>
        <tr class="deduct"><td>Outstanding Advances</td><td>- ${formatAED(result.outstandingAdvances)}</td></tr>
        <tr class="total"><td>NET SETTLEMENT PAYABLE</td><td>${formatAED(result.totalNet)}</td></tr>
      </table>

      <div class="footer">
        Generated by Workloop — UAE Payroll &amp; HRMS &nbsp;|&nbsp; ${formatDateUAE(today)}
      </div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <div className="modal-overlay">
      <div className="modal modal-lg">
        <div className="modal-header">
          <h3><Calculator size={16} style={{ marginRight:6 }}/>End-of-Service Settlement — {employee.name}</h3>
          <button className="btn btn-ghost btn-icon" onClick={onClose}><X size={18}/></button>
        </div>

        <div className="modal-body">
          {/* Input section */}
          <div className="card mb-4">
            <div className="card-header"><h3>Settlement Parameters</h3></div>
            <div className="card-body">
              <div className="form-grid form-grid-2">
                <div className="form-group">
                  <label>Employment Start Date</label>
                  <input
                    className="form-control"
                    type="date"
                    value={employee.startDate || employee.employmentStartDate || ''}
                    disabled
                  />
                  <span className="hint">From employee profile</span>
                </div>
                <div className="form-group">
                  <label>Termination / Last Working Date *</label>
                  <input
                    className="form-control"
                    type="date"
                    value={terminationDate}
                    onChange={e => { setTerminationDate(e.target.value); setResult(null); }}
                  />
                </div>
                <div className="form-group">
                  <label>Basic Salary (AED)</label>
                  <input className="form-control" value={formatAED(employee.basicSalary)} disabled/>
                  <span className="hint">Gratuity is calculated on basic salary only</span>
                </div>
                <div className="form-group">
                  <label>Outstanding Salary Advances (AED)</label>
                  <input
                    className="form-control"
                    type="number"
                    min="0"
                    step="0.01"
                    value={outstandingAdvances}
                    onChange={e => { setOutstandingAdvances(e.target.value); setResult(null); }}
                    placeholder="0.00"
                  />
                  <span className="hint">Will be deducted from total settlement</span>
                </div>
              </div>
              <div style={{ marginTop:16 }}>
                <button className="btn btn-primary" onClick={calculate}>
                  <Calculator size={15}/> Calculate Settlement
                </button>
              </div>
            </div>
          </div>

          {/* Results */}
          {result && (
            <>
              {/* Service summary */}
              <div className="alert alert-info mb-4">
                <div>
                  <strong>{result.employee}</strong> &nbsp;|&nbsp;
                  Start: {formatDateUAE(result.startDate)} &nbsp;|&nbsp;
                  End: {formatDateUAE(result.terminationDate)} &nbsp;|&nbsp;
                  Service: <strong>{result.yearsOfService.toFixed(2)} years</strong>
                </div>
              </div>

              <div className="form-grid form-grid-2" style={{ gap:16 }}>
                {/* Pro-rata salary */}
                <div className="card">
                  <div className="card-header"><h3>Final Month Salary (Pro-rata)</h3></div>
                  <div className="card-body" style={{ padding:0 }}>
                    <table>
                      <tbody>
                        <tr>
                          <td>Days Worked</td>
                          <td className="text-right">{result.daysWorked} / {result.daysInMonth} days</td>
                        </tr>
                        <tr>
                          <td>Basic Salary</td>
                          <td className="text-right">{formatAED(result.basicSalary)}</td>
                        </tr>
                        {result.housingAllowance > 0 && (
                          <tr><td>Housing Allowance</td><td className="text-right">{formatAED(result.housingAllowance)}</td></tr>
                        )}
                        {result.transportAllowance > 0 && (
                          <tr><td>Transport Allowance</td><td className="text-right">{formatAED(result.transportAllowance)}</td></tr>
                        )}
                        {result.otherAllowances > 0 && (
                          <tr><td>Other Allowances</td><td className="text-right">{formatAED(result.otherAllowances)}</td></tr>
                        )}
                        <tr style={{ background:'var(--success-light)', fontWeight:700 }}>
                          <td>Pro-rata Final Salary</td>
                          <td className="text-right" style={{ color:'var(--success)' }}>{formatAED(result.proRataFinalSalary)}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>

                {/* Gratuity */}
                <div className="card">
                  <div className="card-header"><h3>Gratuity / EOSB (Art. 51)</h3></div>
                  <div className="card-body" style={{ padding:0 }}>
                    {!result.gratuity.eligible ? (
                      <div style={{ padding:'16px 20px', color:'var(--gray-500)', fontSize:13 }}>
                        <strong>Not eligible</strong> — less than 1 year of service.
                        <br/>Service: {result.gratuity.years.toFixed(2)} years
                      </div>
                    ) : (
                      <table>
                        <tbody>
                          <tr>
                            <td>Years of Service</td>
                            <td className="text-right">{result.gratuity.years.toFixed(2)} years</td>
                          </tr>
                          <tr>
                            <td>Daily Rate (Basic/30)</td>
                            <td className="text-right">{formatAED(result.gratuity.dailyRate)}</td>
                          </tr>
                          <tr>
                            <td>Calculation</td>
                            <td className="text-right text-sm" style={{ color:'var(--gray-500)' }}>{result.gratuity.breakdown}</td>
                          </tr>
                          <tr>
                            <td>Gratuity (before cap)</td>
                            <td className="text-right">{formatAED(result.gratuity.gratuityRaw)}</td>
                          </tr>
                          <tr>
                            <td>2-Year Cap</td>
                            <td className="text-right text-sm" style={{ color:'var(--gray-500)' }}>{formatAED(result.gratuity.cap)}</td>
                          </tr>
                          <tr style={{ background:'var(--success-light)', fontWeight:700 }}>
                            <td>Gratuity Payable {result.gratuity.capped ? '(capped)' : ''}</td>
                            <td className="text-right" style={{ color:'var(--success)' }}>{formatAED(result.gratuity.gratuityCapped)}</td>
                          </tr>
                        </tbody>
                      </table>
                    )}
                  </div>
                </div>
              </div>

              {/* Net settlement */}
              <div className="card mt-4">
                <div className="card-header"><h3>Total Settlement Summary</h3></div>
                <div className="card-body" style={{ padding:0 }}>
                  <table>
                    <tbody>
                      <tr>
                        <td>Pro-rata Final Salary</td>
                        <td className="text-right">{formatAED(result.proRataFinalSalary)}</td>
                      </tr>
                      <tr>
                        <td>Gratuity / EOSB</td>
                        <td className="text-right">{formatAED(result.gratuity.gratuityCapped)}</td>
                      </tr>
                      <tr style={{ fontWeight:600 }}>
                        <td>Total Gross</td>
                        <td className="text-right">{formatAED(result.totalGross)}</td>
                      </tr>
                      {result.outstandingAdvances > 0 && (
                        <tr style={{ color:'var(--danger)' }}>
                          <td>Less: Outstanding Advances</td>
                          <td className="text-right">- {formatAED(result.outstandingAdvances)}</td>
                        </tr>
                      )}
                      <tr style={{ background:'var(--primary-light)', fontWeight:700, fontSize:15 }}>
                        <td style={{ color:'var(--primary-dark)' }}>NET SETTLEMENT PAYABLE</td>
                        <td className="text-right" style={{ color:'var(--primary)' }}>{formatAED(result.totalNet)}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </>
          )}
        </div>

        <div className="modal-footer">
          <button className="btn btn-outline" onClick={onClose}>Close</button>
          {result && (
            <button className="btn btn-primary" onClick={printSettlement}>
              <Download size={15}/> Print / Save Settlement
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
