/**
 * OffboardingModal.jsx — Structured offboarding workflow for terminated employees.
 *
 * Features:
 *   - Auto-creates or loads existing offboarding checklist on mount
 *   - Clearance task checklist with one-click check/uncheck and custom task add
 *   - Visa cancellation status tracking (Not Started → Initiated → GDRFA → Cancelled)
 *   - NOC letter generator (printable HTML)
 *   - Experience letter generator (printable HTML)
 *   - Links to End-of-Service calculator (layers on top)
 *   - Checklist progress bar
 */
import { useState, useEffect } from 'react';
import { X, CheckSquare, Square, Plus, Trash2, Printer, Calculator, CheckCircle, ClipboardList } from 'lucide-react';
import { formatDateUAE } from '../utils/uaeValidators';
import { safePrint } from '../utils/safePrint';
import {
  getOffboardingChecklist, createOffboardingChecklist,
  getOffboardingTasks, updateOffboardingTask, addOffboardingTask, deleteOffboardingTask,
  saveOffboardingVisaStatus, completeOffboardingChecklist,
} from '../utils/storage';
import EndOfServiceScreen from './EndOfServiceScreen';

// ── Visa cancellation status options ─────────────────────────────────────────
const VISA_STATUSES = [
  { value: 'not_started',     label: 'Not Started',          badge: 'badge-gray'  },
  { value: 'initiated',       label: 'Initiated',            badge: 'badge-blue'  },
  { value: 'submitted_gdrfa', label: 'Submitted to GDRFA',   badge: 'badge-amber' },
  { value: 'cancelled',       label: 'Cancelled',            badge: 'badge-green' },
];

// ── Letter generators ─────────────────────────────────────────────────────────

function printNOC(employee) {
  const today = new Date().toLocaleDateString('en-AE', { day: '2-digit', month: 'long', year: 'numeric' });
  const startLabel = employee.startDate
    ? new Date(employee.startDate).toLocaleDateString('en-AE', { day: '2-digit', month: 'long', year: 'numeric' })
    : null;
  const endLabel = employee.terminationDate
    ? new Date(employee.terminationDate).toLocaleDateString('en-AE', { day: '2-digit', month: 'long', year: 'numeric' })
    : null;

  const html = `<!DOCTYPE html><html><head><title>NOC — ${employee.name}</title>
<style>
  body { font-family: Arial, sans-serif; padding: 60px; color: #333; max-width: 700px; margin: auto; }
  h1   { font-size: 20px; text-align: center; margin-bottom: 4px; }
  .sub { text-align: center; font-size: 14px; color: #555; margin-bottom: 32px; border-bottom: 1px solid #e5e7eb; padding-bottom: 16px; }
  p    { font-size: 14px; line-height: 1.75; margin-bottom: 14px; }
  .sig { margin-top: 64px; display: flex; justify-content: space-between; }
  .sig-block { width: 44%; border-top: 2px solid #374151; padding-top: 10px; font-size: 13px; }
  .footer { margin-top: 48px; font-size: 11px; color: #9ca3af; text-align: center; }
  @media print { button { display: none !important; } }
</style></head><body>

<h1>NO OBJECTION CERTIFICATE</h1>
<div class="sub">To Whom It May Concern</div>

<p>Date: <strong>${today}</strong></p>

<p>This is to certify that <strong>${employee.name}</strong>${employee.empNo ? ` (Employee No. ${employee.empNo})` : ''} was employed with our company as <strong>${employee.jobTitle || 'Employee'}</strong>${employee.department ? ` in the ${employee.department} department` : ''}.${startLabel ? ` Employment commenced on <strong>${startLabel}</strong>` : ''}${endLabel ? ` and concluded on <strong>${endLabel}</strong>` : ''}.</p>

<p>We hereby confirm that we have <strong>no objection</strong> to ${employee.name} seeking employment with any other company or organisation, and we extend our full support for their future career endeavours.</p>

<p>During their tenure, ${employee.name} performed their duties professionally and to the satisfaction of the company. This NOC is issued upon the request of the employee for their personal use.</p>

<div class="sig">
  <div class="sig-block">
    Authorised Signatory<br/><br/>
    Name: ___________________<br/>
    Designation: _____________<br/>
    Date: ____________________
  </div>
  <div class="sig-block" style="text-align:center; padding-top: 24px;">
    Company Stamp
  </div>
</div>

<div class="footer">Generated by Workloop — UAE Payroll &amp; HRMS</div>
</body></html>`;

  const win = safePrint(html);
  if (win) win.print();
}

function printExperienceLetter(employee) {
  const today = new Date().toLocaleDateString('en-AE', { day: '2-digit', month: 'long', year: 'numeric' });
  const startLabel = employee.startDate
    ? new Date(employee.startDate).toLocaleDateString('en-AE', { day: '2-digit', month: 'long', year: 'numeric' })
    : null;
  const endLabel = employee.terminationDate
    ? new Date(employee.terminationDate).toLocaleDateString('en-AE', { day: '2-digit', month: 'long', year: 'numeric' })
    : null;

  // Approximate service period
  let serviceText = '';
  if (employee.startDate && employee.terminationDate) {
    const months = Math.round(
      (new Date(employee.terminationDate) - new Date(employee.startDate)) / (1000 * 60 * 60 * 24 * 30.44)
    );
    const yrs  = Math.floor(months / 12);
    const mons = months % 12;
    serviceText = yrs > 0
      ? `${yrs} year${yrs !== 1 ? 's' : ''}${mons > 0 ? ` and ${mons} month${mons !== 1 ? 's' : ''}` : ''}`
      : `${months} month${months !== 1 ? 's' : ''}`;
  }

  const html = `<!DOCTYPE html><html><head><title>Experience Letter — ${employee.name}</title>
<style>
  body { font-family: Arial, sans-serif; padding: 60px; color: #333; max-width: 700px; margin: auto; }
  h1   { font-size: 20px; text-align: center; margin-bottom: 4px; }
  .sub { text-align: center; font-size: 14px; color: #555; margin-bottom: 32px; border-bottom: 1px solid #e5e7eb; padding-bottom: 16px; }
  p    { font-size: 14px; line-height: 1.75; margin-bottom: 14px; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  td    { padding: 9px 14px; border: 1px solid #e5e7eb; font-size: 13px; }
  td:first-child { font-weight: 600; color: #555; width: 36%; background: #f9fafb; }
  .sig { margin-top: 64px; display: flex; justify-content: space-between; }
  .sig-block { width: 44%; border-top: 2px solid #374151; padding-top: 10px; font-size: 13px; }
  .footer { margin-top: 48px; font-size: 11px; color: #9ca3af; text-align: center; }
  @media print { button { display: none !important; } }
</style></head><body>

<h1>EXPERIENCE LETTER</h1>
<div class="sub">To Whom It May Concern</div>

<p>Date: <strong>${today}</strong></p>

<p>This is to certify that <strong>${employee.name}</strong> was employed with our organisation. We confirm the following details of their service:</p>

<table>
  <tr><td>Full Name</td><td>${employee.name}</td></tr>
  ${employee.empNo   ? `<tr><td>Employee No.</td><td>${employee.empNo}</td></tr>` : ''}
  <tr><td>Designation</td><td>${employee.jobTitle || '—'}</td></tr>
  ${employee.department ? `<tr><td>Department</td><td>${employee.department}</td></tr>` : ''}
  ${startLabel ? `<tr><td>Date of Joining</td><td>${startLabel}</td></tr>` : ''}
  ${endLabel   ? `<tr><td>Last Working Day</td><td>${endLabel}</td></tr>` : ''}
  ${serviceText ? `<tr><td>Total Service Period</td><td>${serviceText}</td></tr>` : ''}
  ${employee.contractType ? `<tr><td>Contract Type</td><td>${employee.contractType}</td></tr>` : ''}
</table>

<p>During their tenure, ${employee.name} performed their duties diligently and professionally. We wish them every success in their future career.</p>

<p>This letter is issued at the request of the employee for whatever purpose it may serve.</p>

<div class="sig">
  <div class="sig-block">
    Authorised Signatory<br/><br/>
    Name: ___________________<br/>
    Designation: _____________<br/>
    Date: ____________________
  </div>
  <div class="sig-block" style="text-align:center; padding-top: 24px;">
    Company Stamp
  </div>
</div>

<div class="footer">Generated by Workloop — UAE Payroll &amp; HRMS</div>
</body></html>`;

  const win = safePrint(html);
  if (win) win.print();
}

// ── Main component ────────────────────────────────────────────────────────────
export default function OffboardingModal({ employee, onClose }) {
  const [checklist, setChecklist] = useState(null);
  const [tasks, setTasks]         = useState([]);
  const [loading, setLoading]     = useState(true);

  const [visaStatus, setVisaStatus] = useState('not_started');
  const [visaDate,   setVisaDate]   = useState('');
  const [visaSaving, setVisaSaving] = useState(false);
  const [visaSaved,  setVisaSaved]  = useState(false);

  const [newTaskName, setNewTaskName] = useState('');
  const [addingTask,  setAddingTask]  = useState(false);

  const [completing, setCompleting] = useState(false);
  const [showEOS,    setShowEOS]    = useState(false);

  // Load or create checklist on mount
  useEffect(() => {
    const init = async () => {
      try {
        let cl = await getOffboardingChecklist(employee.id);
        if (!cl) cl = await createOffboardingChecklist(employee.id);
        setChecklist(cl);
        setVisaStatus(cl.visaCancellationStatus);
        setVisaDate(cl.visaCancellationDate || '');
        const tks = await getOffboardingTasks(cl.id);
        setTasks(tks);
      } catch (err) {
        console.error('Offboarding init:', err);
      } finally {
        setLoading(false);
      }
    };
    init();
  }, [employee.id]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Task handlers ─────────────────────────────────────────────────────────

  const handleToggleTask = async (task) => {
    const newCompleted = !task.completed;
    // Optimistic update
    setTasks(prev => prev.map(t => t.id === task.id ? { ...t, completed: newCompleted } : t));
    try {
      const updated = await updateOffboardingTask(task.id, {
        completed:   newCompleted,
        completedBy: '',
        notes:       task.notes,
      });
      setTasks(prev => prev.map(t => t.id === task.id ? updated : t));
    } catch (err) {
      setTasks(prev => prev.map(t => t.id === task.id ? task : t)); // revert
      alert('Failed to update task: ' + err.message);
    }
  };

  const handleAddTask = async () => {
    if (!newTaskName.trim() || !checklist) return;
    setAddingTask(true);
    try {
      const saved = await addOffboardingTask(checklist.id, newTaskName.trim());
      setTasks(prev => [...prev, saved]);
      setNewTaskName('');
    } catch (err) {
      alert('Failed to add task: ' + err.message);
    } finally {
      setAddingTask(false);
    }
  };

  const handleDeleteTask = async (task) => {
    if (!window.confirm(`Remove "${task.taskName}"?`)) return;
    setTasks(prev => prev.filter(t => t.id !== task.id)); // optimistic
    try {
      await deleteOffboardingTask(task.id);
    } catch (err) {
      setTasks(prev => [...prev, task].sort((a, b) => a.sortOrder - b.sortOrder)); // restore
      alert('Failed: ' + err.message);
    }
  };

  // ── Visa status handler ───────────────────────────────────────────────────

  const handleSaveVisaStatus = async () => {
    if (!checklist) return;
    setVisaSaving(true);
    try {
      const updated = await saveOffboardingVisaStatus(checklist.id, {
        visaCancellationStatus: visaStatus,
        visaCancellationDate:   visaDate,
      });
      setChecklist(updated);
      setVisaSaved(true);
      setTimeout(() => setVisaSaved(false), 3000);
    } catch (err) {
      alert('Failed to save visa status: ' + err.message);
    } finally {
      setVisaSaving(false);
    }
  };

  // ── Complete offboarding ──────────────────────────────────────────────────

  const handleComplete = async () => {
    if (!checklist) return;
    const incomplete = tasks.filter(t => !t.completed).length;
    if (incomplete > 0) {
      if (!window.confirm(`${incomplete} task${incomplete !== 1 ? 's are' : ' is'} still pending. Mark offboarding as completed anyway?`)) return;
    } else {
      if (!window.confirm('Mark this offboarding as fully completed?')) return;
    }
    setCompleting(true);
    try {
      const updated = await completeOffboardingChecklist(checklist.id);
      setChecklist(updated);
    } catch (err) {
      alert('Failed: ' + err.message);
    } finally {
      setCompleting(false);
    }
  };

  // ── Derived ───────────────────────────────────────────────────────────────

  const completedCount = tasks.filter(t => t.completed).length;
  const totalCount     = tasks.length;
  const pct            = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;
  const visaStatusObj  = VISA_STATUSES.find(v => v.value === (checklist?.visaCancellationStatus || 'not_started'));

  // Layer EOS calculator on top when requested
  if (showEOS) {
    return <EndOfServiceScreen employee={employee} onClose={() => setShowEOS(false)} />;
  }

  return (
    <div className="modal-overlay">
      <div className="modal modal-lg" style={{ maxWidth: 700 }}>
        <div className="modal-header">
          <h3><ClipboardList size={16} style={{ marginRight: 6 }} />Offboarding — {employee.name}</h3>
          <button className="btn btn-ghost btn-icon" onClick={onClose}><X size={18}/></button>
        </div>

        <div className="modal-body">
          {loading ? (
            <div style={{ textAlign: 'center', color: 'var(--gray-400)', padding: '36px 0', fontSize: 14 }}>
              Setting up checklist…
            </div>
          ) : (
            <>
              {/* Employee summary */}
              <div style={{ background: '#f8fafc', borderRadius: 10, padding: '12px 18px', marginBottom: 20, border: '1px solid var(--gray-200)' }}>
                <div style={{ display: 'flex', gap: 28, flexWrap: 'wrap', alignItems: 'flex-start' }}>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-500)', marginBottom: 3 }}>Job Title</div>
                    <div style={{ fontWeight: 600, fontSize: 14 }}>{employee.jobTitle || '—'}</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-500)', marginBottom: 3 }}>Department</div>
                    <div style={{ fontWeight: 600, fontSize: 14 }}>{employee.department || '—'}</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-500)', marginBottom: 3 }}>Termination Date</div>
                    <div style={{ fontWeight: 600, fontSize: 14 }}>{formatDateUAE(employee.terminationDate) || '—'}</div>
                  </div>
                  <div>
                    <div style={{ fontSize: 11, color: 'var(--gray-500)', marginBottom: 3 }}>Checklist</div>
                    <span className={`badge ${checklist?.status === 'completed' ? 'badge-green' : 'badge-blue'}`} style={{ fontSize: 11 }}>
                      {checklist?.status === 'completed' ? '✓ Completed' : 'In Progress'}
                    </span>
                  </div>
                </div>
              </div>

              {/* Progress bar */}
              <div style={{ marginBottom: 20 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, fontWeight: 600, marginBottom: 6 }}>
                  <span style={{ color: 'var(--gray-700)' }}>Clearance Progress</span>
                  <span style={{ color: pct === 100 ? 'var(--success)' : 'var(--gray-500)' }}>
                    {completedCount}/{totalCount} tasks ({pct}%)
                  </span>
                </div>
                <div style={{ height: 8, background: 'var(--gray-200)', borderRadius: 6, overflow: 'hidden' }}>
                  <div style={{
                    height: '100%',
                    width: `${pct}%`,
                    background: pct === 100 ? 'var(--success)' : 'var(--primary)',
                    borderRadius: 6,
                    transition: 'width 0.3s',
                  }} />
                </div>
              </div>

              {/* Visa Cancellation */}
              <div className="card mb-4">
                <div className="card-header">
                  <h3>Visa Cancellation</h3>
                  {visaStatusObj && (
                    <span className={`badge ${visaStatusObj.badge}`} style={{ fontSize: 11 }}>
                      {visaStatusObj.label}
                    </span>
                  )}
                </div>
                <div className="card-body">
                  <div className="form-grid form-grid-2" style={{ gap: 12, marginBottom: 12 }}>
                    <div className="form-group">
                      <label>Cancellation Status</label>
                      <select className="form-control" value={visaStatus} onChange={e => setVisaStatus(e.target.value)}>
                        {VISA_STATUSES.map(v => <option key={v.value} value={v.value}>{v.label}</option>)}
                      </select>
                    </div>
                    <div className="form-group">
                      <label>Date <span style={{ fontWeight: 400, color: 'var(--gray-400)' }}>(optional)</span></label>
                      <input className="form-control" type="date" value={visaDate} onChange={e => setVisaDate(e.target.value)} />
                    </div>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    <button className="btn btn-primary btn-sm" onClick={handleSaveVisaStatus} disabled={visaSaving}>
                      {visaSaving ? 'Saving…' : 'Save Status'}
                    </button>
                    {visaSaved && (
                      <span style={{ fontSize: 12, color: 'var(--success)', display: 'flex', alignItems: 'center', gap: 4 }}>
                        <CheckCircle size={13} /> Saved
                      </span>
                    )}
                  </div>
                </div>
              </div>

              {/* Clearance Checklist */}
              <div className="card mb-4">
                <div className="card-header">
                  <h3>Clearance Checklist</h3>
                  <span style={{ fontSize: 12, color: 'var(--gray-500)' }}>Click a task to toggle completion</span>
                </div>
                <div style={{ padding: 0 }}>
                  {tasks.length === 0 ? (
                    <div style={{ padding: '16px 20px', color: 'var(--gray-400)', fontSize: 13 }}>No tasks yet.</div>
                  ) : (
                    tasks.map((task, idx) => (
                      <div
                        key={task.id}
                        style={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: 12,
                          padding: '11px 16px',
                          borderBottom: idx < tasks.length - 1 ? '1px solid var(--gray-100)' : 'none',
                          cursor: 'pointer',
                          background: task.completed ? 'rgba(16,185,129,0.03)' : 'white',
                          transition: 'background 0.15s',
                        }}
                        onClick={() => handleToggleTask(task)}
                      >
                        <div style={{ flexShrink: 0, color: task.completed ? 'var(--success)' : 'var(--gray-300)' }}>
                          {task.completed
                            ? <CheckSquare size={18} />
                            : <Square size={18} />
                          }
                        </div>
                        <div style={{ flex: 1 }}>
                          <div style={{
                            fontSize: 14,
                            fontWeight: task.completed ? 400 : 500,
                            color: task.completed ? 'var(--gray-400)' : 'var(--gray-800)',
                            textDecoration: task.completed ? 'line-through' : 'none',
                          }}>
                            {task.taskName}
                          </div>
                          {task.completed && task.completedAt && (
                            <div style={{ fontSize: 11, color: 'var(--gray-400)', marginTop: 2 }}>
                              Completed {task.completedAt.split('T')[0]}
                            </div>
                          )}
                        </div>
                        <button
                          className="btn btn-ghost btn-icon btn-sm text-danger"
                          title="Remove task"
                          style={{ flexShrink: 0 }}
                          onClick={e => { e.stopPropagation(); handleDeleteTask(task); }}
                        >
                          <Trash2 size={13} />
                        </button>
                      </div>
                    ))
                  )}

                  {/* Add custom task row */}
                  <div style={{ padding: '12px 16px', borderTop: tasks.length > 0 ? '1px solid var(--gray-100)' : 'none' }}>
                    <div style={{ display: 'flex', gap: 8 }}>
                      <input
                        className="form-control"
                        style={{ flex: 1 }}
                        placeholder="Add a custom task…"
                        value={newTaskName}
                        onChange={e => setNewTaskName(e.target.value)}
                        onKeyDown={e => { if (e.key === 'Enter') handleAddTask(); }}
                      />
                      <button
                        className="btn btn-primary btn-sm"
                        onClick={handleAddTask}
                        disabled={!newTaskName.trim() || addingTask}
                      >
                        <Plus size={13} style={{ marginRight: 4 }} />
                        {addingTask ? 'Adding…' : 'Add'}
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              {/* Letters & Actions */}
              <div className="card">
                <div className="card-header">
                  <h3>Letters &amp; Settlement</h3>
                </div>
                <div className="card-body">
                  <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
                    <button
                      className="btn btn-ghost btn-sm"
                      style={{ border: '1px solid var(--gray-300)' }}
                      onClick={() => printNOC(employee)}
                    >
                      <Printer size={13} style={{ marginRight: 5 }} />NOC Letter
                    </button>
                    <button
                      className="btn btn-ghost btn-sm"
                      style={{ border: '1px solid var(--gray-300)' }}
                      onClick={() => printExperienceLetter(employee)}
                    >
                      <Printer size={13} style={{ marginRight: 5 }} />Experience Letter
                    </button>
                    <button
                      className="btn btn-ghost btn-sm"
                      style={{ border: '1px solid #d97706', color: '#b45309' }}
                      onClick={() => setShowEOS(true)}
                    >
                      <Calculator size={13} style={{ marginRight: 5 }} />EOS Calculator
                    </button>
                  </div>
                  <p style={{ fontSize: 12, color: 'var(--gray-400)', marginTop: 10, marginBottom: 0 }}>
                    Letters open in a new tab ready to print. EOS Calculator computes the full UAE gratuity settlement.
                  </p>
                </div>
              </div>
            </>
          )}
        </div>

        <div className="modal-footer">
          <button className="btn btn-outline" onClick={onClose}>Close</button>
          {!loading && checklist?.status !== 'completed' && (
            <button className="btn btn-primary" onClick={handleComplete} disabled={completing}>
              <CheckCircle size={14} style={{ marginRight: 5 }} />
              {completing ? 'Completing…' : 'Mark as Completed'}
            </button>
          )}
          {checklist?.status === 'completed' && (
            <span className="badge badge-green" style={{ fontSize: 13, padding: '6px 14px' }}>
              ✓ Offboarding Complete
            </span>
          )}
        </div>
      </div>
    </div>
  );
}
