#!/bin/sh
set -eu

psql --set ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<'SQL'
\getenv workloop_migration_password WORKLOOP_MIGRATION_PASSWORD
\getenv workloop_runtime_password WORKLOOP_RUNTIME_PASSWORD
\getenv keycloak_db_password KEYCLOAK_DB_PASSWORD

CREATE ROLE workloop_migration LOGIN PASSWORD :'workloop_migration_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE workloop_runtime LOGIN PASSWORD :'workloop_runtime_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE keycloak LOGIN PASSWORD :'keycloak_db_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE workloop OWNER workloop_migration;
CREATE DATABASE keycloak OWNER keycloak;

REVOKE ALL PRIVILEGES ON DATABASE postgres FROM PUBLIC;
REVOKE ALL PRIVILEGES ON DATABASE workloop FROM PUBLIC;
REVOKE ALL PRIVILEGES ON DATABASE keycloak FROM PUBLIC;

GRANT CONNECT, TEMPORARY ON DATABASE workloop TO workloop_runtime;
SQL
